/**
 * 初衷小鹿 — LanguageContext.tsx
 * 支援語言：繁中 (zh-TW)、英文 (en)、日文 (ja)、韓文 (ko)
 */
import React, { createContext, useContext, useState, useCallback } from "react";

export type Language = "zh-TW" | "en" | "ja" | "ko";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "zh-TW",
  setLang: () => {},
  t: (key) => key,
});

export function useLanguage() {
  return useContext(LanguageContext);
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem("deer-lang") as Language | null;
    return saved || "zh-TW";
  });

  const setLang = useCallback((newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem("deer-lang", newLang);
  }, []);

  const t = useCallback(
    (key: string): string => {
      const dict = translations[lang];
      return dict[key] ?? translations["zh-TW"][key] ?? key;
    },
    [lang]
  );

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// 翻譯資料
// ─────────────────────────────────────────────────────────────────────────────
type TranslationDict = Record<string, string>;
type Translations = Record<Language, TranslationDict>;

const translations: Translations = {
  "zh-TW": {
    // ── Navbar ──
    "nav.home": "首頁",
    "nav.brand": "品牌故事",
    "nav.menu": "菜單",
    "nav.space": "空間體驗",
    "nav.awards": "獲獎殊榮/雜誌專訪",
    "nav.transport": "交通與停車",
    "nav.crem": "CRÈM 蛋糕上桌預訂",
    "nav.reserve": "立即訂位",
    "nav.shop": "生鮮商店",
    "nav.close": "關閉選單",
    "nav.open": "開啟選單",

    // ── Footer ──
    "footer.contact": "Contact",
    "footer.hours": "Hours",
    "footer.follow": "Follow",
    "footer.findUs": "Find Us",
    "footer.address.city": "台北市信義區",
    "footer.address.street": "忠孝東路四段 553 巷 6 弄 15 號",
    "footer.navigate": "立即導航",
    "footer.viewOnMaps": "在 Google Maps 查看",
    "footer.gettingHere": "Getting Here",
    "footer.transportDesc": "捷運、開車、停車建議——詳見交通與停車頁面",
    "footer.transportLink": "交通與停車 →",
    "footer.copyright": "© 2026 初衷小鹿 Deer's Hotpot Bistro. All rights reserved.",
    "footer.hours.mon": "星期一",
    "footer.hours.tue": "星期二",
    "footer.hours.wed": "星期三",
    "footer.hours.thu": "星期四",
    "footer.hours.fri": "星期五",
    "footer.hours.sat": "星期六",
    "footer.hours.sun": "星期日",

    // ── Home ──
    "home.tagline": "Deer's Hotpot Bistro · Taipei Xinyi",
    "home.hero.line1": "不是一頓火鍋，",
    "home.hero.line2": "是一場有節奏的",
    "home.hero.line3": "餐桌體驗。",
    "home.hero.cta": "預約一場餐桌",
    "home.philosophy.label": "Our Philosophy",
    "home.philosophy.title1": "我們不做熱鬧的火鍋。",
    "home.philosophy.title2": "我們在意的，",
    "home.philosophy.title3": "是一場餐桌的節奏。",
    "home.philosophy.desc": "前菜、湯底、熟成肉品、酒搭配、甜點收尾。\n每一個環節，都是節奏的一部分。",
    "home.cores.label": "What We Do",
    "home.cores.title": "三個核心，構成一場完整的餐桌。",
    "home.cores.meat.en": "The Cut",
    "home.cores.meat.zh": "熟成肉品",
    "home.cores.meat.subtitle": "熟成肉品．肉的嚴選專家",
    "home.cores.meat.desc": "經過濕式熟成處理，保留肉汁、脂肪香氣、提升柔嫩度，適合火鍋這樣的短時間加熱方式，吃得到肉的原味。",
    "home.cores.soup.en": "The Broth",
    "home.cores.soup.zh": "日本頂級乾貨",
    "home.cores.soup.subtitle": "『日本頂級乾貨』上湯的層次底蘊",
    "home.cores.soup.desc": "金黃透亮的乾貨上湯，經長時間熬煮而成。鰹魚的煙燻深度、昆布、椎茸的溫潤菌香，在口中層層展開，越喝越有鮮甜厚度。",
    "home.cores.dessert.en": "The Finale",
    "home.cores.dessert.zh": "甜點與酒感",
    "home.cores.dessert.subtitle": "從主鍋延伸到甜點與酒感",
    "home.cores.dessert.desc": "真正被記住的體驗，是從入座一路延伸至餐後。甜點、酒櫃與桌邊節奏共同完成這場晚餐。",
    "home.narrative.label": "The Experience",
    "home.narrative.title": "一場餐桌的節奏，是這樣展開的。",
    "home.narrative.step1.title": "前菜，讓味蕾開始",
    "home.narrative.step1.body": "不是填飽，是鋪陳。\n一道前菜，讓整場餐桌的節奏慢慢展開。",
    "home.narrative.step2.title": "湯開始後，節奏慢了下來",
    "home.narrative.step2.body": "清澈的上湯，不搶食材的味道。\n讓每一口都有它應有的位置。",
    "home.narrative.step3.title": "肉，不需要調味",
    "home.narrative.step3.body": "熟成的肉品，自己就是答案。\n只需要湯，只需要時間。",
    "home.narrative.step4.title": "最後，留一點時間給甜點",
    "home.narrative.step4.body": "一場好的餐桌，不應該在主食結束後就散場。\n甜點，是把時間留給彼此的方式。",
    "home.space.label": "The Space",
    "home.space.title": "為了那些不該被打擾的時刻",
    "home.space.desc": "我們在意的，不只是食物本身。\n是那些值得好好享受的時刻。",
    "home.trust.label": "Trust",
    "home.trust.rating": "4.6 顆星",
    "home.trust.ratingDesc": "Google 評分",
    "home.trust.reviews": "500+ 則評論",
    "home.trust.reviewsDesc": "真實顧客回饋",
    "home.trust.years": "5+ 年",
    "home.trust.yearsDesc": "品牌深耕",
    "home.cta.label": "Reservation",
    "home.cta.title": "預約一場屬於你的餐桌",
    "home.cta.desc": "每一張桌子，都是一個值得好好享受的時刻。",
    "home.cta.btn": "立即訂位",
    "home.notice.label": "近期營業時間調整",

    // ── Home (TrustSection) ──
    "home.trust.googleReviews": "Google Reviews",
    "home.trust.reviewCount": "{n} 則 Google 評論",
    "home.trust.viewReviews": "查看 Google 評論 ↗",
    "home.trust.authentic1": "我們不送禮換評論，",
    "home.trust.authentic2": "也不請客人留下評價。",
    "home.trust.authenticSub": "每一則評論，都是真實的用餐記憶。",
    "home.trust.recognition": "Recognition",
    "home.trust.award1.year": "2023 · 台北市府鍋物大賽",
    "home.trust.award1.title": "2023 台北十強鍋物",
    "home.trust.award2.year": "2024 · 台北市府鍋物大賽",
    "home.trust.award2.title": "2024 台灣 30 大鍋物",
    "home.trust.award3.year": "2024 · &Premium Japan",
    "home.trust.award3.title": "日本生活品味雜誌《&Premium》年度收錄",
    "home.trust.award3.desc": "以「美好生活指南」為概念，廣受歡迎且充滿質感氛圍的日本生活雜誌",

    // ── Home (CRÈM section) ──
    "home.crem.imgTitle": "一條龍慶祝服務，從餐桌到蛋糕。",
    "home.crem.imgTitleMobile1": "一條龍慶祝服務，",
    "home.crem.imgTitleMobile2": "從餐桌到蛋糕。",
    "home.crem.desc1": "初衷小鹿 × CRÈM 聯名，",
    "home.crem.desc2": "讓每一場慶祝都有專屬蛋糕。",
    "home.crem.descSub": "由兩個品牌共創一場慶祝的完整設計。",
    "home.crem.step1.label": "預訂座位",
    "home.crem.step1.desc": "透過 Inline 線上預訂，備註慶祝人與就餐時段",
    "home.crem.step2.label": "選擇蛋糕",
    "home.crem.step2.desc": "至 CRÈM 官網挑選專屬慶祝蛋糕，備註小鹿訂位資訊",
    "home.crem.step3.label": "小鹿代勞",
    "home.crem.step3.desc": "我們全程跟進 CRÈM 確認，確保蛋糕按時就位",
    "home.crem.step4.label": "餐桌驚喜",
    "home.crem.step4.desc": "餐後蛋糕登場，不需擔心一切，只需就座享受這場慶祝",
    "home.crem.ctaDesc": "這是一場不需要擔心任何事的專屬慶祝。",
    "home.crem.ctaBtn": "預約一場慶祝餐桌",

    // ── Home (CTA section) ──
    "home.cta.finalTitle": "預約一場餐桌",
    "home.cta.finalDesc": "把時間，留給重要的人。",
    "home.cta.finalBtn": "立即預約",

    // ── Home (Cores updated subtitles) ──
    "home.cores.soup.subtitle2": "靜岡本枯節 · 北海道羅臼昆布 · 宮崎香信椎茸",
    "home.cores.soup.desc2": "三種頂級日本乾貨，長時慢熬。鮮甜清澈，不添加人工甘味——湯底是料理的靈魂，不是背景。",
    "home.cores.meat.subtitle2": "SRF 極黑和牛 · 伊比利豬 · 草飼羊",
    "home.cores.meat.desc2": "西餐等級肉種，濕式熟成處理。保留肉汁與脂肪香氣，讓火鍋也能有一點講究。",
    "home.cores.dessert.subtitle2": "專業甜點師 · 侍酒師嚴選酒單",
    "home.cores.dessert.desc2": "甜點不是配角。從紅白氣泡酒搭配到餐後甜點收尾，這是我們反骨的個性——一場餐桌，不該在主食後就散場。",
    "home.cores.title2": "三核心，構成一場完整的餐桌",

    // ── Home (Space section updated) ──
    "home.space.cta": "空間體驗⇢",
    "home.space.title2": "一場屬於你們的餐桌，",
    "home.space.title2b": "不需要理由。",

    // ── Home (Narrative CTA) ──
    "home.narrative.ctaReady": "準備好了嗎？",
    "home.narrative.ctaBtn": "預約一場餐桌",

    // ── Brand ──
    "brand.hero.label": "Brand Story",
    "brand.hero.title": "品牌故事",
    "brand.hero.subtitle": "人生最容易被遗忘的，就是初衷。",
    "brand.origin.label": "The Origin",
    "brand.origin.title": "一段環島，一個頓悟。",
    "brand.origin.p1": "創辦人小鹿早期由於迷惑自己的人生方向，開啟了一段環島之旅。直到旅途到台東初鹿時，受到一對原住民夫妻熱情的款待。",
    "brand.origin.p2": "那對夫妻告訴他，「鹿」在原住民裡象徵著「純潔」、「簡單」。相處的過程中，他發現夫妻就生活並不富裕，卻過得很滿足快樂。",
    "brand.origin.p3": "就像「鹿」的意思一樣，這種心靈上純粹的快樂，似乎就是人生最終要追求的目的地。在這趤旅程結束後，創辦人審視了自己的「初衷」，也找回初心，希望帶給更多迷途中的人，能重新找回屬於自己初衷「快樂的意義」，因而將店名取為「初衷小鹿」。",
    "brand.stats.founded": "創立於台北信義區",
    "brand.stats.rating": "Google 評分",
    "brand.stats.top10": "2023 台北鍋物大賽十強",
    "brand.stats.top30": "2024 全台灣 30 大鍋物",
    "brand.stats.reviews": "則評論",
    "brand.commitment.label": "Our Commitment",
    "brand.commitment.title": "我們的居持",
    "brand.commitment.c1.en": "Broth First",
    "brand.commitment.c1.zh": "天然上湯",
    "brand.commitment.c1.desc": "以齃節柴魚、多樣蔬果長時熬製，不添加人工甘味劑。湯底澄清透明，是食材本身的誠意。",
    "brand.commitment.c2.en": "Curated Cuts",
    "brand.commitment.c2.zh": "嚴選肉品",
    "brand.commitment.c2.desc": "經過濕式熟成處理，保留肉汁、脂肪香氣、提升柔嫩度，依部位特性搦配渮燒方式，每一片都有它應在的位置。",
    "brand.commitment.c3.en": "Present Service",
    "brand.commitment.c3.zh": "在場服務",
    "brand.commitment.c3.desc": "服務不催促節奏，不打擾對話。在場，但不佔据。讓餐桌屬於你們，讓時間屬於這一刻。",
    "brand.commitment.c4.en": "CRÈM Dessert",
    "brand.commitment.c4.zh": "慶祝蛋糕",
    "brand.commitment.c4.desc": "與 CRÈM 甄點品牌合作，提供一條龍慶祝服務，從餐桌到蛋糕，讓每個重要時刻都更加完整。",
    "brand.quote.label": "Our Philosophy",
    "brand.quote.text": "「湯底從來不是背景，而是料理的靈魂。」",
    "brand.quote.desc": "以日本頂級乾貨與天然蔬果長時熬製，將鮮味慢慢收進每一口之中，只留食材本身的誠意。每一口湯，都是這份初衷最直接的表達。",
    "brand.quote.en": "Soul in every broth.",
    "brand.section1.label": "The Beginning",
    "brand.section1.title": "一個關於「初衷」的故事",
    "brand.section2.label": "The Philosophy",
    "brand.section2.title": "我們相信，一頓好的火鍋，是有節奏的。",
    "brand.section3.label": "The Name",
    "brand.section3.title": "為什麼是「鹿」？",
    "brand.cta.title": "來一場有節奏的餐桌",
    "brand.cta.btn": "立即訂位",

    // ── Reservation ──
    "reservation.hero.label": "Reservation",
    "reservation.hero.title": "預約一場餐桌",
    "reservation.hero.subtitle": "把時間，留給重要的人。",
    "reservation.booking.label": "Online Booking",
    "reservation.booking.note": "如遇訂位系統問題，亦可透過 Instagram 或 Facebook 私訊聯絡我們。",
    "reservation.notice.label": "Booking Notice",
    "reservation.notice.title": "訂位公告",
    "reservation.notice.n1.en": "Minimum Spend",
    "reservation.notice.n1.zh": "最低消費",
    "reservation.notice.n1.content": "晚餐時段每位 NT$600（以單人獨立計算）\n商業午餐每位 NT$300\n以上價格均加收一成服務費",
    "reservation.notice.n2.en": "Hours",
    "reservation.notice.n2.zh": "營業時間",
    "reservation.notice.n2.content": "星期日\u300011:30–15:00\u300017:30–22:30\n星期一\u300012:00–15:00\u300018:00–22:00\n星期二\u300012:00–15:00\u300018:00–22:00\n星期三\u300012:00–15:00\u300018:00–22:00\n星期四\u300012:00–15:00\u300018:00–22:00\n星期五\u300012:00–15:00\u300017:30–22:30\n星期六\u300011:30–15:00\u300017:30–22:30",
    "reservation.notice.n3.en": "Location",
    "reservation.notice.n3.zh": "地址",
    "reservation.notice.n3.content": "台北市信義區\n忠孝東路四段 553 巷 6 弄 15 號",
    "reservation.notice.n4.en": "Beverage Policy",
    "reservation.notice.n4.zh": "飲品規定",
    "reservation.notice.n4.content": "本餐廳僅提供 NATURA 微礦水或微礦氣泡水\n禁止飲用烈酒\n自備酒水酌收開瓶費葡萄酒每瓶 NT$500",
    "reservation.notes.label": "Important Notes",
    "reservation.notes.b1": "建議提前 3–7 天預約，以確保您偏好的時段與席位。",
    "reservation.notes.b2": "如有特殊需求（包廂、慶祝佈置、飲食限制），請於備注欄說明。",
    "reservation.notes.b3": "部分餐點可能會因供貨短缺及品質等因素而無法正常供應。",
    "reservation.notes.b4": "每份套餐均含一份前菜、綜合菜盤、副餐及甜點。",
    "reservation.notes.b5": "商業午餐僅平日供應，假日及例假日不供應。",
    "reservation.celeb.label": "Celebration Service",
    "reservation.celeb.title": "全新服務｜小鹿為您準備慶祝蛋糕",
    "reservation.celeb.desc": "與 CRÈM 鮮奶油專門店合作，您只需在 CRÈM 官網下單，備註訂位大名、日期與時間，我們的人員將自動為您安排製作、配送與蠟燭擺盤上桌，讓甜點成為這個時刻最完整的收尾。",
    "reservation.celeb.s1.step": "01",
    "reservation.celeb.s1.title": "CRÈM 官網下單",
    "reservation.celeb.s1.desc": "前往 CRÈM 預定蛋糕網頁，選擇 4、6、8 吋蛋糕，線上預訂快速方便。",
    "reservation.celeb.s2.step": "02",
    "reservation.celeb.s2.title": "備註訂位資訊",
    "reservation.celeb.s2.desc": "下單時備註訂位大名、日期、時間，省去與餐廳溝通的時間，我們將自動為您安排。",
    "reservation.celeb.s3.step": "03",
    "reservation.celeb.s3.title": "小鹿全程代勞",
    "reservation.celeb.s3.desc": "配送到餐廳、低溫冷藏保存、蠟燭擺盤上桌，讓您專心享受與壽星的用餐時刻。",
    "reservation.celeb.highlights.label": "Service Highlights",
    "reservation.celeb.h1": "預定 4、6、8 吋蛋糕（線上預訂，快速方便）",
    "reservation.celeb.h2": "配送餐廳（省去取貨、送貨交通時間）",
    "reservation.celeb.h3": "低溫冷藏（省去冷藏保存焦慮）",
    "reservation.celeb.h4": "溝通訂位資訊、安排上桌（省去與餐廳溝通時間）",
    "reservation.celeb.h5": "初衷小鹿蠟燭擺盤上桌（省去心意儀式感編排）",
    "reservation.celeb.h6": "專心享受與壽星的用餐時刻",
    "reservation.celeb.cta.ready": "準備好了嗎？",
    "reservation.celeb.cta.desc": "前往 CRÈM 官網選購蛋糕，備註訂位大名、日期與時間，其餘由我們幫您完成。",
    "reservation.celeb.cta.btn": "前往 CRÈM 官網",

    // ── Menu ──
    "menu.hero.label": "Our Menu",
    "menu.hero.title": "每一道，都是節奏的一部分。",
    "menu.reserve.btn": "立即訂位",
    "menu.note": "菜單內容與價格可能依季節調整，以現場為準。",
    "menu.hero.h1": "菜單",
    "menu.hint": "點擊圖片可放大查看 · 左右滑動或使用 ← → 方向鍵翻頁 · 價格均加收一成服務費",
    "menu.lightbox.close": "點擊任意處關閉",
    "menu.cat.all": "全部菜單",
    "menu.cat.surf": "海陸套餐",
    "menu.cat.beef": "牛肉套餐",
    "menu.cat.pork": "豬肉套餐",
    "menu.cat.lamb": "羊肉套餐",
    "menu.cat.seafood": "海鮮套餐",
    "menu.cat.chicken": "雞肉 / 蔬食",
    "menu.cat.sides": "單點配料",
    "menu.cat.lunch": "商業午餐",
    "menu.cat.drinks": "全部酒水",
    "menu.drink.glass": "紅｜白｜氣泡/杯",
    "menu.drink.red": "紅酒/瓶",
    "menu.drink.white": "白酒/瓶",
    "menu.drink.sparkling": "氣泡酒/瓶",
    "menu.drink.beer": "啤酒",
    "menu.drink.juice": "果汁/氣泡飲",
    "menu.label.intro": "品牌理念",
    "menu.label.surf": "海陸套餐",
    "menu.label.beef": "牛肉套餐",
    "menu.label.pork": "豬肉套餐",
    "menu.label.chicken": "雞肉 / 蔬食",
    "menu.label.lamb": "羊肉套餐",
    "menu.label.seafood": "海鮮套餐",
    "menu.label.sides1": "美味關係",
    "menu.label.sides2": "手工漿 / 餃",
    "menu.label.sides3": "雲吞 / 丸類",
    "menu.label.sides4": "海鮮單點",
    "menu.label.sides5": "魚類單點",
    "menu.label.sides6": "蔬菜副餐",
    "menu.label.lunch1": "商業午餐",
    "menu.label.lunch2": "午餐牛肉",
    "menu.label.lunch3": "午餐豬肉",
    "menu.label.lunch4": "午餐羊 / 海鮮",
    "menu.label.lunch5": "午餐附餐甜點",
    "menu.label.quote": "品牌語句",

    // ── Space ──
    "space.hero.label": "Space Experience",
    "space.hero.title": "空間體驗",
    "space.intro.p1": "空間不只是背景。\n它是這頓飯的第一句話。",
    "space.intro.p2": "黑磚、木質、暖銅燈具。\n每一處細節，都是為了讓你專注於眼前的人。",
    "space.sec1.label": "01 — Exterior",
    "space.sec1.title": "外觀與入口",
    "space.sec2.label": "02 — Dining Area",
    "space.sec2.title": "用餐空間",
    "space.quote.en": "\"The right distance between tables is a form of respect.\"",
    "space.quote.zh": "桌與桌之間的距離，是一種尊重。",
    "space.sec3.label": "03 — Details & Bar",
    "space.sec3.title": "細節與吧台",
    "space.sec4.label": "04 — Location",
    "space.sec4.title": "位置與導航",
    "space.navigate.btn": "↗ 立即導航",
    "space.googlemaps.btn": "在 Google Maps 查看",
    "space.cta.quote": "有些氛圍，\n是照片說不清楚的。",
    "space.reserve.btn": "Reserve a Table",

    // ── Awards ──
    "awards.hero.label": "Achievements & Press",
    "awards.hero.title": "獲獎殊榮／雜誌專訪",
    "awards.hero.desc": "每一份認可，都是一個提醒——\n讓我們繼續把每一場餐桌做得更好。",
    "awards.taiwan30.label": "2024 · 台北市府鍋物大賽",
    "awards.taiwan30.title": "2024 台灣 30 大鍋物",
    "awards.taiwan30.subtitle": "Taiwan International Hotpot Awards — Top 30",
    "awards.taiwan30.desc": "從台北到全台，在更大的競技場中再次獲得評審認可，\n入選台灣年度三十大鍋物餐廳。",
    "awards.premium.label": "2024 · &Premium Japan",
    "awards.premium.title": "日本生活品味雜誌《&Premium》",
    "awards.premium.subtitle": "The Guide To A Better Life",
    "awards.premium.desc": "以「美好生活指南」為核心概念的日本知名生活雜誌《&Premium》，\n將初衷小鹿列入台灣精選餐廳名嫌。",
    "awards.taipei10.label": "2023 · 台北市鍋際大賞",
    "awards.taipei10.title": "台北市政府鍋際大賞 TOP 10",
    "awards.taipei10.subtitle": "Taipei International Hotpot Awards — Top 10",
    "awards.taipei10.desc": "由台北市政府主辦的「美食在台北·鍋際大賞」，\n初衷小鹿在全台數千間參賽餐廳中脫穎而出，入選十強。",
    "awards.press.label": "Press Coverage",
    "awards.press.title": "媒體報導",
    "awards.media.label": "Press Coverage",
    "awards.media.title": "媒體報導",
    "awards.media.vogue.title": "Vogue Taiwan 專訪",
    "awards.media.vogue.desc": "時尚指標媒體 Vogue Taiwan 特別報導，深入介紹初衷小鹿的品牌理念與餐桌哲學。",
    "awards.media.chinatimes.title": "工商時報報導",
    "awards.media.chinatimes.desc": "財經媒體工商時報以餐飲品牌視角，深度報導初衷小鹿的品牌故事與市場定位。",
    "awards.media.elle.title": "ELLE 生活指南",
    "awards.media.elle.desc": "國際時尚雜誌 ELLE 將初衷小鹿列入台北大巨蛋周邊美食精選名單。",
    "awards.media.or.title": "旅讀 Or 精選",
    "awards.media.or.desc": "旅遊生活雜誌旅讀 Or 特別推薦，列入台北精選餐廳名單。",
    "awards.reviews.label": "Google Reviews",
    "awards.reviews.title": "4.6 顆星的後面",
    "awards.reviews.count": "{count} 則真實評論",
    "awards.reviews.count.fallback": "1,600+ 則真實評論",
    "awards.reviews.view": "在 Google Maps 查看全部評論 ↗",
    "awards.reviews.p1": "從不請客人主動評論",
    "awards.reviews.p2": "從不做評論送禮活動",
    "awards.reviews.p3": "從不花錢購買假評論",
    "awards.reviews.desc": "一點一滴收集每一位客人真實的反饋，\n成為我們每個進步的方針。",
    "awards.cta.text": "這些認可，讓我們繼續做好\n每一場餐桌。",
    "awards.reserve.btn": "預約一場餐桌",
    "awards.cta.title": "這些認可，讓我們繼續做好\n每一場餐桌。",
    "awards.cta.btn": "預約一場餐桌",
    "awards.premium.jul.desc": "2024 年 7 月號《&Premium》以「台灣精選餐廳」為主題，將初衷小鹿列入推薦名單，介紹其獨特的鍋物體驗與品牌哲學。",
    "awards.premium.oct.desc": "2024 年 10 月號《&Premium》以「小さな家に暮らす」為主題，再次收錄初衷小鹿，肯定其作為台北代表性餐廳的地位。",
    "awards.google.reviewsUnit": "則評論",
    "awards.google.reviewsDefault": "1,626 則評論",
    "awards.google.viewAll": "在 Google Maps 查看全部評論 ↗",
    "awards.google.rule1": "從不請客人主動評論",
    "awards.google.rule2": "從不做評論送禮活動",
    "awards.google.rule3": "從不花錢購買假評論",
    "awards.google.desc": "一點一滴收集每一位客人真實的反饋，\n成為我們每個進步的方針。",

    // ── Transport ──
    "transport.hero.label": "Getting Here",
    "transport.hero.title": "如何順利抵達\n初衷小鹿",
    "transport.hero.subtitle": "位於信義區巷弄內\n建議提前查看交通與停車方式",
    "transport.hero.navigate.btn": "導航至餐廳",
    "transport.hero.parking.btn": "查看停車建議",
    "transport.address.label": "地址",
    "transport.navigate.btn": "導航至餐廳",
    "transport.mrt.label": "捷運",
    "transport.bus.label": "公車",
    "transport.drive.label": "開車",
    "transport.parking.label": "停車",
    "transport.overview.label": "Getting Here",
    "transport.overview.title": "選擇最適合你的抵達方式",
    "transport.mrt.title": "搭乘捷運",
    "transport.mrt.line": "板南線·市政府站",
    "transport.mrt.line.sub": "Bannan Line · City Hall Station",
    "transport.mrt.step1": "由 1 號出口出站",
    "transport.mrt.step2": "沿忠孝東路向東步行",
    "transport.mrt.step3": "步行約 400 公尺，5 分鐘可抵達",
    "transport.mrt.navigate.btn": "捷運導航路線",
    "transport.bus.title": "搭乘公車",
    "transport.bus.stop.label": "公車站名",
    "transport.bus.routes.label": "可乘路線",
    "transport.bus.navigate.btn": "公車導航路線",
    "transport.parking.title": "開車前往",
    "transport.parking.desc": "初衷小鹿位於巷弄內，周邊路邊停車位有限，建議直接停放至鄰近停車場後步行前往。",
    "transport.parking.walk": "步行距離",
    "transport.parking.feature": "特點",
    "transport.parking.spaces": "車位",
    "transport.parking.address": "地址",
    "transport.parking.navigate.btn": "導航至停車場",
    "transport.lot1.badge": "首選",
    "transport.lot1.name": "松山高中地下停車場",
    "transport.lot1.address": "基隆路一段 156 號地下",
    "transport.lot1.walk": "步行約 3 分鐘",
    "transport.lot1.feature": "距離最近，適合快速抵達",
    "transport.lot1.spaces": "約 226 格，24 小時營業",
    "transport.lot2.badge": "備選",
    "transport.lot2.name": "俥亭停車基隆路二場",
    "transport.lot2.address": "基隆路一段 176 巷 1 號",
    "transport.lot2.walk": "步行約 2 分鐘",
    "transport.lot2.feature": "鄰近餐廳，適合快速停車",
    "transport.lot2.spaces": "24 小時營業，車位數量請現場確認",
    "transport.lot3.badge": "假日備案",
    "transport.lot3.name": "臺北文創大樓收費停車場",
    "transport.lot3.address": "信義區菸廠路 88 號",
    "transport.lot3.walk": "步行約 8 分鐘",
    "transport.lot3.feature": "松菸園區內，車位充足，適合假日尖峰時段",
    "transport.lot3.spaces": "24 小時營業，建議提前查詢即時車位",
    "transport.decision.label": "Quick Guide",
    "transport.decision.title": "不知道怎麼來？\n可以這樣選",
    "transport.map.label": "Illustrated Map",
    "transport.map.title": "周邊交通示意圖",
    "transport.map.zoom": "點擊放大",
    "transport.sticky.navigate": "導航至餐廳",
    "transport.sticky.mrt": "捷運怎麼走",
    "transport.sticky.parking": "停車建議",
    "transport.card.mrt.en": "MRT",
    "transport.card.mrt.zh": "捷運",
    "transport.card.mrt.desc": "市政府站 1 號出口\n步行約 5 分鐘",
    "transport.card.bus.en": "Bus",
    "transport.card.bus.zh": "公車",
    "transport.card.bus.desc": "市府轉運站周邊\n多路公車可達",
    "transport.card.drive.en": "Drive",
    "transport.card.drive.zh": "開車",
    "transport.card.drive.desc": "建議停放鄰近停車場\n步行 5–10 分鐘",
    "transport.card.taxi.en": "Taxi / Uber",
    "transport.card.taxi.zh": "計程車/Uber",
    "transport.card.taxi.desc": "可輸入地址直達\n計程車/小車均可導航",
    "transport.decision.d1.situation": "想最方便",
    "transport.decision.d1.suggestion": "搭捷運到市政府站，再步行前往",
    "transport.decision.d2.situation": "從市區出發",
    "transport.decision.d2.suggestion": "搭公車或捷運均可，交通順暢",
    "transport.decision.d3.situation": "帶家人一起來",
    "transport.decision.d3.suggestion": "開車並停放鄰近停車場，步行就能抵達",
    "transport.decision.d4.situation": "不營業時間該怎辦",
    "transport.decision.d4.suggestion": "請參考首頁的營業時間表或直接聯絡我們",

    // ── Experience ──
    "experience.hero.label": "The Experience",
    "experience.hero.title": "一場餐桌的節奏",
    "experience.reserve.btn": "預約體驗",

    // ── CRÈM ──
    "crem.hero.label": "CRÈM Dessert",
    "crem.hero.title": "蛋糕上桌，甜點收尾",
    "crem.reserve.btn": "預訂蛋糕",
    "crem.banner.label": "Exclusive Collaboration",
    "crem.banner.title": "CRÈM蛋糕上桌預訂",
    "crem.banner.subtitle": "× CRÈM 聯名共創",
    "crem.banner.desc": "由兩個品牌共創一場慶祝的完整設計。\n從餐桌到蛋糕，讓每個重要時刻都更加完整。",
    "crem.about.label": "About CRÈM",
    "crem.about.title": "一個專注於奶油的甜點品牌",
    "crem.about.desc1": "CRÈM 專注於創作高品質的奶油甜點，圍繞著「鮮奶油 & 奶油」這核心食材。\n通過對奶油的深入研究，將不同原物料與奶油搭配，創造出每一款奶油甜點的味覺平衡與極致風味。",
    "crem.about.desc2": "對 CRÈM 來說，奶油的選擇並非一味追求頂級，而是以對奶油的專業了解，\n發掘其與其他食材的完美相容性，讓顧客能在一口之間感受細膩與豐富的層次。",
    "crem.about.btn": "前往 CRÈM 官網",
    "crem.steps.label": "How It Works",
    "crem.steps.title": "四個步驟，\n完成一場完整的慶祝。",
    "crem.steps.hint": "全程由初衷小鹿協助溝通，您只需安心就座。",
    "crem.step1.title": "預訂座位",
    "crem.step1.desc": "透過 Inline 線上預訂初衷小鹿，備註慶祝人姓名與就餐時段。",
    "crem.step2.title": "選擇蛋糕",
    "crem.step2.desc": "前往 CRÈM 官網（crem.tw）挑選專屬慶祝蛋糕，備註初衷小鹿訂位資訊。",
    "crem.step3.title": "小鹿代勞",
    "crem.step3.desc": "我們全程跟進 CRÈM 確認，確保蛋糕在對的時間準時就位。",
    "crem.step4.title": "餐桌驚喜",
    "crem.step4.desc": "餐後蛋糕登場，不需擔心任何事，只需就座享受這場慶祝。",
    "crem.cta.title": "準備好讓這場慶祝\n更加完整了嗎？",
    "crem.cta.btn1": "預約初衷小鹿",
    "crem.cta.btn2": "前往 CRÈM 選蛋糕",

    // ── Common ──
    "common.reserve": "立即訂位",
    "common.learnMore": "了解更多",
    "common.back": "返回",
  },

  en: {
    // ── Navbar ──
    "nav.home": "Home",
    "nav.brand": "Our Story",
    "nav.menu": "Menu",
    "nav.space": "The Space",
    "nav.awards": "Awards & Press",
    "nav.transport": "Getting Here",
    "nav.crem": "CRÈM Cake Reservation",
    "nav.reserve": "Reserve Now",
    "nav.shop": "Fresh Market",
    "nav.close": "Close Menu",
    "nav.open": "Open Menu",

    // ── Footer ──
    "footer.contact": "Contact",
    "footer.hours": "Hours",
    "footer.follow": "Follow",
    "footer.findUs": "Find Us",
    "footer.address.city": "Xinyi District, Taipei",
    "footer.address.street": "No. 15, Alley 6, Lane 553, Zhongxiao E. Rd. Sec. 4",
    "footer.navigate": "Get Directions",
    "footer.viewOnMaps": "View on Google Maps",
    "footer.gettingHere": "Getting Here",
    "footer.transportDesc": "MRT, driving & parking — see Getting Here page",
    "footer.transportLink": "Getting Here →",
    "footer.copyright": "© 2026 Deer's Hotpot Bistro. All rights reserved.",
    "footer.hours.mon": "Monday",
    "footer.hours.tue": "Tuesday",
    "footer.hours.wed": "Wednesday",
    "footer.hours.thu": "Thursday",
    "footer.hours.fri": "Friday",
    "footer.hours.sat": "Saturday",
    "footer.hours.sun": "Sunday",

    // ── Home ──
    "home.tagline": "Deer's Hotpot Bistro · Taipei Xinyi",
    "home.hero.line1": "Not just a hotpot,",
    "home.hero.line2": "but a rhythmic",
    "home.hero.line3": "dining experience.",
    "home.hero.cta": "Reserve a Table",
    "home.philosophy.label": "Our Philosophy",
    "home.philosophy.title1": "We don't do loud hotpot.",
    "home.philosophy.title2": "What we care about",
    "home.philosophy.title3": "is the rhythm of a meal.",
    "home.philosophy.desc": "Starter, broth, aged meat, wine pairing, dessert finale.\nEvery moment is part of the rhythm.",
    "home.cores.label": "What We Do",
    "home.cores.title": "Three pillars. One complete dining experience.",
    "home.cores.meat.en": "The Cut",
    "home.cores.meat.zh": "Aged Meat",
    "home.cores.meat.subtitle": "Aged Meat · Curated with Precision",
    "home.cores.meat.desc": "Wet-aged to retain juiciness, fat aroma, and tenderness — perfectly suited for the brief heat of hotpot, letting the natural flavors shine.",
    "home.cores.soup.en": "The Broth",
    "home.cores.soup.zh": "Premium Japanese Dashi",
    "home.cores.soup.subtitle": "Premium Japanese Dashi — Layers of Depth",
    "home.cores.soup.desc": "A golden, translucent broth slow-cooked to perfection. The smoky depth of katsuobushi, the warmth of kombu and shiitake — unfolding layer by layer with every sip.",
    "home.cores.dessert.en": "The Finale",
    "home.cores.dessert.zh": "Dessert & Wine",
    "home.cores.dessert.subtitle": "From the pot to dessert and wine",
    "home.cores.dessert.desc": "A truly memorable experience extends beyond the main course. Dessert, the wine cabinet, and the table's rhythm together complete the evening.",
    "home.narrative.label": "The Experience",
    "home.narrative.title": "This is how a meal unfolds.",
    "home.narrative.step1.title": "The starter sets the stage",
    "home.narrative.step1.body": "Not to fill, but to prepare.\nA starter that slowly opens the rhythm of the meal.",
    "home.narrative.step2.title": "When the broth begins, pace slows",
    "home.narrative.step2.body": "A clear broth that never overpowers.\nEvery bite finds its rightful place.",
    "home.narrative.step3.title": "The meat needs no seasoning",
    "home.narrative.step3.body": "Aged meat is its own answer.\nJust broth. Just time.",
    "home.narrative.step4.title": "Leave a little time for dessert",
    "home.narrative.step4.body": "A great meal shouldn't end when the main course does.\nDessert is how we give time back to each other.",
    "home.space.label": "The Space",
    "home.space.title": "For moments that shouldn't be interrupted",
    "home.space.desc": "We care about more than the food itself.\nThese are moments worth savoring.",
    "home.trust.label": "Trust",
    "home.trust.rating": "4.6 Stars",
    "home.trust.ratingDesc": "Google Rating",
    "home.trust.reviews": "500+ Reviews",
    "home.trust.reviewsDesc": "Real Guest Feedback",
    "home.trust.years": "5+ Years",
    "home.trust.yearsDesc": "Brand Heritage",
    "home.cta.label": "Reservation",
    "home.cta.title": "Reserve your table",
    "home.cta.desc": "Every table is a moment worth savoring.",
    "home.cta.btn": "Reserve Now",
    "home.notice.label": "Recent Hours Update",

    // ── Home (TrustSection) ──
    "home.trust.googleReviews": "Google Reviews",
    "home.trust.reviewCount": "{n} Google Reviews",
    "home.trust.viewReviews": "View Google Reviews ↗",
    "home.trust.authentic1": "We don't offer gifts for reviews,",
    "home.trust.authentic2": "nor do we ask guests to leave ratings.",
    "home.trust.authenticSub": "Every review is a genuine dining memory.",
    "home.trust.recognition": "Recognition",
    "home.trust.award1.year": "2023 · Taipei City Hotpot Competition",
    "home.trust.award1.title": "2023 Taipei Top 10 Hotpot",
    "home.trust.award2.year": "2024 · Taipei City Hotpot Competition",
    "home.trust.award2.title": "2024 Taiwan Top 30 Hotpot",
    "home.trust.award3.year": "2024 · &Premium Japan",
    "home.trust.award3.title": "Featured in Japanese lifestyle magazine \u300a&Premium\u300b",
    "home.trust.award3.desc": "A beloved Japanese lifestyle magazine known for its refined, quality-driven aesthetic",

    // ── Home (CRÈM section) ──
    "home.crem.imgTitle": "Full-service celebration, from table to cake.",
    "home.crem.imgTitleMobile1": "Full-service celebration,",
    "home.crem.imgTitleMobile2": "from table to cake.",
    "home.crem.desc1": "Deer's Hotpot Bistro × CRÈM collaboration,",
    "home.crem.desc2": "every celebration deserves its own cake.",
    "home.crem.descSub": "Two brands co-creating a complete celebration experience.",
    "home.crem.step1.label": "Book a Seat",
    "home.crem.step1.desc": "Reserve via Inline, note the celebrant and dining time",
    "home.crem.step2.label": "Choose a Cake",
    "home.crem.step2.desc": "Browse CRÈM's website for your celebration cake, note your Deer's reservation",
    "home.crem.step3.label": "We Handle It",
    "home.crem.step3.desc": "We coordinate with CRÈM throughout to ensure the cake arrives on time",
    "home.crem.step4.label": "Table Surprise",
    "home.crem.step4.desc": "The cake arrives after dinner — just sit back and enjoy the celebration",
    "home.crem.ctaDesc": "A celebration where you don't need to worry about a thing.",
    "home.crem.ctaBtn": "Reserve a Celebration Table",

    // ── Home (CTA section) ──
    "home.cta.finalTitle": "Reserve a Table",
    "home.cta.finalDesc": "Give your time to the people who matter.",
    "home.cta.finalBtn": "Reserve Now",

    // ── Home (Cores updated subtitles) ──
    "home.cores.soup.subtitle2": "Shizuoka Honkarebushi · Hokkaido Rausu Kombu · Miyazaki Koshin Shiitake",
    "home.cores.soup.desc2": "Three premium Japanese dried ingredients, slow-cooked for hours. Sweet, clear, no artificial flavoring — the broth is the soul of the dish, not the backdrop.",
    "home.cores.meat.subtitle2": "SRF Wagyu · Iberico Pork · Grass-fed Lamb",
    "home.cores.meat.desc2": "Restaurant-grade cuts, wet-aged. Retaining juiciness and fat aroma, bringing a touch of refinement to hotpot.",
    "home.cores.dessert.subtitle2": "Pastry Chef · Sommelier-curated Wine List",
    "home.cores.dessert.desc2": "Dessert is not a supporting act. From sparkling wine pairings to a dessert finale, this is our rebellious spirit — a meal shouldn't end when the main course does.",
    "home.cores.title2": "Three pillars. One complete dining experience.",

    // ── Home (Space section updated) ──
    "home.space.cta": "The Space ⇢",
    "home.space.title2": "A table that belongs to you,",
    "home.space.title2b": "no reason needed.",

    // ── Home (Narrative CTA) ──
    "home.narrative.ctaReady": "Ready?",
    "home.narrative.ctaBtn": "Reserve a Table",

    // ── Brand ──
    "brand.hero.label": "Brand Story",
    "brand.hero.title": "Brand Story",
    "brand.hero.subtitle": "The easiest thing to forget in life is your original intention.",
    "brand.origin.label": "The Origin",
    "brand.origin.title": "A journey around Taiwan, a moment of clarity.",
    "brand.origin.p1": "In the early days, founder Xiao Lu felt lost about the direction of his life and embarked on a journey around Taiwan. When he reached Chulu in Taitung, he was warmly welcomed by an indigenous couple.",
    "brand.origin.p2": "The couple told him that \"deer\" in their culture symbolizes \"purity\" and \"simplicity\". He noticed that despite their modest means, they lived with deep contentment and joy.",
    "brand.origin.p3": "Just like the meaning of \"deer\", this pure spiritual happiness seemed to be the ultimate destination in life. After the journey, he reflected on his own \"original intention\" and found his heart again — hoping to help others rediscover the meaning of happiness, and named the restaurant Deer's Hotpot Bistro.",
    "brand.stats.founded": "Founded in Xinyi, Taipei",
    "brand.stats.rating": "Google Rating",
    "brand.stats.top10": "2023 Taipei Hotpot Top 10",
    "brand.stats.top30": "2024 Taiwan Top 30 Hotpot",
    "brand.stats.reviews": "reviews",
    "brand.commitment.label": "Our Commitment",
    "brand.commitment.title": "Our Commitment",
    "brand.commitment.c1.en": "Broth First",
    "brand.commitment.c1.zh": "Natural Broth",
    "brand.commitment.c1.desc": "Slow-cooked with katsuobushi, vegetables and natural ingredients — no artificial flavor enhancers. Clear and honest, just the integrity of the ingredients.",
    "brand.commitment.c2.en": "Curated Cuts",
    "brand.commitment.c2.zh": "Premium Cuts",
    "brand.commitment.c2.desc": "Wet-aged to preserve juiciness, fat aroma and tenderness. Each cut is matched to its ideal cooking method — every slice has its place.",
    "brand.commitment.c3.en": "Present Service",
    "brand.commitment.c3.zh": "Attentive Service",
    "brand.commitment.c3.desc": "Service that doesn't rush the pace or interrupt conversation. Present, but not intrusive. The table belongs to you; the time belongs to this moment.",
    "brand.commitment.c4.en": "CR\u00c8M Dessert",
    "brand.commitment.c4.zh": "Celebration Cake",
    "brand.commitment.c4.desc": "In partnership with CR\u00c8M, we offer a full-service celebration experience — from the table to the cake, making every important moment complete.",
    "brand.quote.label": "Our Philosophy",
    "brand.quote.text": "\u201cThe broth is never the background — it is the soul of the dish.\u201d",
    "brand.quote.desc": "Slow-cooked with premium Japanese dried ingredients and natural produce, drawing out umami into every sip — leaving only the integrity of the ingredients. Every spoonful of broth is the most direct expression of this original intention.",
    "brand.quote.en": "Soul in every broth.",
    "brand.section1.label": "The Beginning",
    "brand.section1.title": "A story about original intention",
    "brand.section2.label": "The Philosophy",
    "brand.section2.title": "We believe a great hotpot has rhythm.",
    "brand.section3.label": "The Name",
    "brand.section3.title": "Why the deer?",
    "brand.cta.title": "Experience a rhythmic dining table",
    "brand.cta.btn": "Reserve Now",

    // ── Reservation ──
    "reservation.hero.label": "Reservation",
    "reservation.hero.title": "Reserve a Table",
    "reservation.hero.subtitle": "Save the time for the people who matter.",
    "reservation.booking.label": "Online Booking",
    "reservation.booking.note": "If you encounter any issues with the booking system, feel free to contact us via Instagram or Facebook DM.",
    "reservation.notice.label": "Booking Notice",
    "reservation.notice.title": "Booking Information",
    "reservation.notice.n1.en": "Minimum Spend",
    "reservation.notice.n1.zh": "Minimum Spend",
    "reservation.notice.n1.content": "Dinner: NT$600 per person (charged individually)\nBusiness Lunch: NT$300 per person\nAll prices subject to 10% service charge",
    "reservation.notice.n2.en": "Hours",
    "reservation.notice.n2.zh": "Opening Hours",
    "reservation.notice.n2.content": "Sunday\u300011:30–15:00\u300017:30–22:30\nMonday\u300012:00–15:00\u300018:00–22:00\nTuesday\u300012:00–15:00\u300018:00–22:00\nWednesday\u300012:00–15:00\u300018:00–22:00\nThursday\u300012:00–15:00\u300018:00–22:00\nFriday\u300012:00–15:00\u300017:30–22:30\nSaturday\u300011:30–15:00\u300017:30–22:30",
    "reservation.notice.n3.en": "Location",
    "reservation.notice.n3.zh": "Address",
    "reservation.notice.n3.content": "Xinyi District, Taipei\nNo. 15, Alley 6, Lane 553, Zhongxiao E. Rd. Sec. 4",
    "reservation.notice.n4.en": "Beverage Policy",
    "reservation.notice.n4.zh": "Beverage Policy",
    "reservation.notice.n4.content": "We only serve NATURA still or sparkling mineral water\nSpirits are not permitted\nCorkage fee: NT$500 per bottle of wine",
    "reservation.notes.label": "Important Notes",
    "reservation.notes.b1": "We recommend booking 3–7 days in advance to secure your preferred time and seating.",
    "reservation.notes.b2": "For special requests (private room, celebration setup, dietary restrictions), please note them in the comments.",
    "reservation.notes.b3": "Some dishes may be unavailable due to supply or quality reasons.",
    "reservation.notes.b4": "Each set includes an appetizer, assorted vegetable plate, side dish, and dessert.",
    "reservation.notes.b5": "Business lunch is available on weekdays only; not available on weekends or public holidays.",
    "reservation.celeb.label": "Celebration Service",
    "reservation.celeb.title": "New Service | Deer Prepares Your Celebration Cake",
    "reservation.celeb.desc": "In partnership with CRÈM, simply order on the CRÈM website, note your reservation name, date, and time, and our team will handle production, delivery, and candle plating — making your dessert the perfect finale.",
    "reservation.celeb.s1.step": "01",
    "reservation.celeb.s1.title": "Order on CRÈM Website",
    "reservation.celeb.s1.desc": "Visit the CRÈM cake reservation page, choose a 4, 6, or 8-inch cake, and order online quickly and conveniently.",
    "reservation.celeb.s2.step": "02",
    "reservation.celeb.s2.title": "Add Reservation Details",
    "reservation.celeb.s2.desc": "Note your reservation name, date, and time when ordering — no need to contact the restaurant separately. We'll arrange everything automatically.",
    "reservation.celeb.s3.step": "03",
    "reservation.celeb.s3.title": "Deer Handles the Rest",
    "reservation.celeb.s3.desc": "Delivery to the restaurant, refrigerated storage, and candle plating at the table — so you can focus on enjoying the moment with your guest of honor.",
    "reservation.celeb.highlights.label": "Service Highlights",
    "reservation.celeb.h1": "Order 4, 6, or 8-inch cakes (online, fast and easy)",
    "reservation.celeb.h2": "Delivery to restaurant (no pickup or transport needed)",
    "reservation.celeb.h3": "Refrigerated storage (no need to worry about keeping it cold)",
    "reservation.celeb.h4": "Coordinate reservation info and table service (no extra communication needed)",
    "reservation.celeb.h5": "Deer's candle plating presentation (no need to arrange the ceremony yourself)",
    "reservation.celeb.h6": "Focus entirely on enjoying the meal with your guest of honor",
    "reservation.celeb.cta.ready": "Ready to celebrate?",
    "reservation.celeb.cta.desc": "Visit the CRÈM website to choose your cake, note your reservation name, date, and time — we'll take care of the rest.",
    "reservation.celeb.cta.btn": "Visit CRÈM Website",

    // ── Menu ──
    "menu.hero.label": "Our Menu",
    "menu.hero.title": "Every dish, part of the rhythm.",
    "menu.reserve.btn": "Reserve Now",
    "menu.note": "Menu and prices may vary by season. Please confirm on-site.",
    "menu.hero.h1": "Menu",
    "menu.hint": "Click image to enlarge · Swipe or use ← → keys to navigate · All prices subject to 10% service charge",
    "menu.lightbox.close": "CLICK ANYWHERE TO CLOSE",
    "menu.cat.all": "All Menu",
    "menu.cat.surf": "Surf & Turf",
    "menu.cat.beef": "Beef Set",
    "menu.cat.pork": "Pork Set",
    "menu.cat.lamb": "Lamb Set",
    "menu.cat.seafood": "Seafood Set",
    "menu.cat.chicken": "Chicken / Veg",
    "menu.cat.sides": "À la Carte",
    "menu.cat.lunch": "Business Lunch",
    "menu.cat.drinks": "All Drinks",
    "menu.drink.glass": "Red | White | Sparkling / Glass",
    "menu.drink.red": "Red Wine / Bottle",
    "menu.drink.white": "White Wine / Bottle",
    "menu.drink.sparkling": "Sparkling / Bottle",
    "menu.drink.beer": "Beer",
    "menu.drink.juice": "Juice / Soft Drinks",
    "menu.label.intro": "Brand Philosophy",
    "menu.label.surf": "Surf & Turf",
    "menu.label.beef": "Beef Set",
    "menu.label.pork": "Pork Set",
    "menu.label.chicken": "Chicken / Veg",
    "menu.label.lamb": "Lamb Set",
    "menu.label.seafood": "Seafood Set",
    "menu.label.sides1": "Delicious Sides",
    "menu.label.sides2": "Handmade Paste / Dumplings",
    "menu.label.sides3": "Wontons / Balls",
    "menu.label.sides4": "Seafood À la Carte",
    "menu.label.sides5": "Fish À la Carte",
    "menu.label.sides6": "Vegetable Sides",
    "menu.label.lunch1": "Business Lunch",
    "menu.label.lunch2": "Lunch Beef",
    "menu.label.lunch3": "Lunch Pork",
    "menu.label.lunch4": "Lunch Lamb / Seafood",
    "menu.label.lunch5": "Lunch Dessert",
    "menu.label.quote": "Brand Quote",

    // ── Space ──
    "space.hero.label": "Space Experience",
    "space.hero.title": "The Space",
    "space.intro.p1": "The space is more than a backdrop.\nIt is the opening line of this meal.",
    "space.intro.p2": "Dark brick, warm wood, copper lighting.\nEvery detail is designed to keep your focus on the person across from you.",
    "space.sec1.label": "01 — Exterior",
    "space.sec1.title": "Exterior & Entrance",
    "space.sec2.label": "02 — Dining Area",
    "space.sec2.title": "Dining Area",
    "space.quote.en": "\"The right distance between tables is a form of respect.\"",
    "space.quote.zh": "The distance between tables is a form of respect.",
    "space.sec3.label": "03 — Details & Bar",
    "space.sec3.title": "Details & Bar",
    "space.sec4.label": "04 — Location",
    "space.sec4.title": "Location & Navigation",
    "space.navigate.btn": "↗ Navigate",
    "space.googlemaps.btn": "View on Google Maps",
    "space.cta.quote": "Some atmospheres\ncannot be captured in photos.",
    "space.reserve.btn": "Reserve a Table",

    // ── Awards ──
    "awards.hero.label": "Achievements & Press",
    "awards.hero.title": "Awards & Press Features",
    "awards.hero.desc": "Every recognition is a reminder\u2014\nto keep making every dining experience better.",
    "awards.taiwan30.label": "2024 \u00b7 Taipei City Hotpot Awards",
    "awards.taiwan30.title": "2024 Taiwan Top 30 Hotpot",
    "awards.taiwan30.subtitle": "Taiwan International Hotpot Awards \u2014 Top 30",
    "awards.taiwan30.desc": "From Taipei to all of Taiwan, recognized again on a larger stage,\nselected as one of Taiwan's Top 30 hotpot restaurants of the year.",
    "awards.premium.label": "2024 \u00b7 &Premium Japan",
    "awards.premium.title": "Japanese Lifestyle Magazine \u300a&Premium\u300b",
    "awards.premium.subtitle": "The Guide To A Better Life",
    "awards.premium.desc": "Japan's renowned lifestyle magazine &Premium, centered on the concept of 'A Guide to a Better Life',\nfeatured Deer's Hotpot Bistro in its curated Taiwan restaurant selection.",
    "awards.taipei10.label": "2023 \u00b7 Taipei Hotpot Awards",
    "awards.taipei10.title": "Taipei City Government Hotpot Awards TOP 10",
    "awards.taipei10.subtitle": "Taipei International Hotpot Awards \u2014 Top 10",
    "awards.taipei10.desc": "Organized by the Taipei City Government, the 'Gourmet Taipei \u00b7 Hotpot Awards'\nsaw Deer's Hotpot Bistro rise among thousands of competing restaurants to claim a Top 10 spot.",
    "awards.press.label": "Press Coverage",
    "awards.press.title": "Media Features",
    "awards.media.label": "Press Coverage",
    "awards.media.title": "Media Features",
    "awards.media.vogue.title": "Vogue Taiwan Feature",
    "awards.media.vogue.desc": "Vogue Taiwan, the leading fashion media, featured Deer's Hotpot Bistro with an in-depth look at our brand philosophy and dining experience.",
    "awards.media.chinatimes.title": "Commercial Times Coverage",
    "awards.media.chinatimes.desc": "Financial media Commercial Times covered Deer's Hotpot Bistro from a F&B brand perspective, exploring our brand story and market positioning.",
    "awards.media.elle.title": "ELLE Living Guide",
    "awards.media.elle.desc": "International fashion magazine ELLE included Deer's Hotpot Bistro in its curated dining guide around Taipei's Dome of Light area.",
    "awards.media.or.title": "Or Travel Magazine Pick",
    "awards.media.or.desc": "Travel and lifestyle magazine Or specially recommended Deer's Hotpot Bistro in its curated Taipei restaurant list.",
    "awards.reviews.label": "Google Reviews",
    "awards.reviews.title": "Behind the 4.6 Stars",
    "awards.reviews.count": "{count} authentic reviews",
    "awards.reviews.count.fallback": "1,600+ authentic reviews",
    "awards.reviews.view": "View all reviews on Google Maps \u2197",
    "awards.reviews.p1": "We never ask guests to leave reviews",
    "awards.reviews.p2": "We never run review-for-gift promotions",
    "awards.reviews.p3": "We never pay for fake reviews",
    "awards.reviews.desc": "Every piece of genuine feedback from our guests,\ncollected one by one, guides every step of our improvement.",
    "awards.cta.text": "These recognitions keep us committed\nto making every dining experience better.",
    "awards.reserve.btn": "Reserve a Table",
    "awards.cta.title": "These recognitions keep us committed\nto making every dining experience better.",
    "awards.cta.btn": "Reserve a Table",
    "awards.premium.jul.desc": "The July 2024 issue of &Premium featured Deer's Hotpot Bistro in its 'Curated Taiwan Restaurants' theme, introducing its unique hotpot experience and brand philosophy.",
    "awards.premium.oct.desc": "The October 2024 issue of &Premium once again featured Deer's Hotpot Bistro, affirming its position as a landmark Taipei restaurant.",
    "awards.google.reviewsUnit": "reviews",
    "awards.google.reviewsDefault": "1,626 reviews",
    "awards.google.viewAll": "View all reviews on Google Maps \u2197",
    "awards.google.rule1": "We never ask guests to leave reviews",
    "awards.google.rule2": "We never run review-for-gift promotions",
    "awards.google.rule3": "We never pay for fake reviews",
    "awards.google.desc": "Every piece of genuine feedback from our guests,\ncollected one by one, guides every step of our improvement.",

    // ── Transport ──
    "transport.hero.label": "Getting Here",
    "transport.hero.title": "How to Find\nDeer's Hotpot Bistro",
    "transport.hero.subtitle": "Tucked in a quiet alley in Xinyi\nWe recommend checking transport options in advance",
    "transport.hero.navigate.btn": "Navigate to Restaurant",
    "transport.hero.parking.btn": "View Parking Options",
    "transport.address.label": "Address",
    "transport.navigate.btn": "Get Directions",
    "transport.mrt.label": "MRT",
    "transport.bus.label": "Bus",
    "transport.drive.label": "By Car",
    "transport.parking.label": "Parking",
    "transport.overview.label": "Getting Here",
    "transport.overview.title": "Choose Your Best Route",
    "transport.mrt.title": "By MRT",
    "transport.mrt.line": "Bannan Line · City Hall Station",
    "transport.mrt.line.sub": "Bannan Line · City Hall Station",
    "transport.mrt.step1": "Exit from Exit 1",
    "transport.mrt.step2": "Walk east along Zhongxiao E. Rd.",
    "transport.mrt.step3": "About 400m, a 5-minute walk",
    "transport.mrt.navigate.btn": "MRT Navigation",
    "transport.bus.title": "By Bus",
    "transport.bus.stop.label": "Bus Stop",
    "transport.bus.routes.label": "Available Routes",
    "transport.bus.navigate.btn": "Bus Navigation",
    "transport.parking.title": "By Car",
    "transport.parking.desc": "Street parking near the restaurant is limited. We recommend parking at a nearby lot and walking over.",
    "transport.parking.walk": "Walking Distance",
    "transport.parking.feature": "Features",
    "transport.parking.spaces": "Spaces",
    "transport.parking.address": "Address",
    "transport.parking.navigate.btn": "Navigate to Parking",
    "transport.lot1.badge": "Best Choice",
    "transport.lot1.name": "Songshan High School Underground Parking",
    "transport.lot1.address": "B1, No. 156, Keelung Rd., Sec. 1",
    "transport.lot1.walk": "~3 min walk",
    "transport.lot1.feature": "Closest option, ideal for quick arrival",
    "transport.lot1.spaces": "~226 spaces, open 24 hrs",
    "transport.lot2.badge": "Alternative",
    "transport.lot2.name": "Chuting Parking Keelung Rd. Lot 2",
    "transport.lot2.address": "No. 1, Ln. 176, Keelung Rd., Sec. 1",
    "transport.lot2.walk": "~2 min walk",
    "transport.lot2.feature": "Near the restaurant, great for quick parking",
    "transport.lot2.spaces": "Open 24 hrs, check availability on-site",
    "transport.lot3.badge": "Weekend Backup",
    "transport.lot3.name": "Taipei Creative Park Paid Parking",
    "transport.lot3.address": "No. 88, Yanchang Rd., Xinyi Dist.",
    "transport.lot3.walk": "~8 min walk",
    "transport.lot3.feature": "Inside Songshan Cultural Park, ample spaces for peak hours",
    "transport.lot3.spaces": "Open 24 hrs, check real-time availability in advance",
    "transport.decision.label": "Quick Guide",
    "transport.decision.title": "Not sure how to get here?\nHere are some options",
    "transport.map.label": "Illustrated Map",
    "transport.map.title": "Area Transport Map",
    "transport.map.zoom": "Click to Enlarge",
    "transport.sticky.navigate": "Navigate",
    "transport.sticky.mrt": "MRT Directions",
    "transport.sticky.parking": "Parking",
    "transport.card.mrt.en": "MRT",
    "transport.card.mrt.zh": "MRT",
    "transport.card.mrt.desc": "City Hall Station Exit 1\n~5 min walk",
    "transport.card.bus.en": "Bus",
    "transport.card.bus.zh": "Bus",
    "transport.card.bus.desc": "Near City Hall Bus Terminal\nMultiple routes available",
    "transport.card.drive.en": "Drive",
    "transport.card.drive.zh": "Drive",
    "transport.card.drive.desc": "Park at nearby lots\n5–10 min walk",
    "transport.card.taxi.en": "Taxi / Uber",
    "transport.card.taxi.zh": "Taxi / Uber",
    "transport.card.taxi.desc": "Enter address for direct arrival\nAll ride-hailing apps supported",
    "transport.decision.d1.situation": "Most convenient",
    "transport.decision.d1.suggestion": "Take MRT to City Hall Station and walk over",
    "transport.decision.d2.situation": "Coming from downtown",
    "transport.decision.d2.suggestion": "Bus or MRT both work well",
    "transport.decision.d3.situation": "Coming with family",
    "transport.decision.d3.suggestion": "Drive and park at a nearby lot, then walk",
    "transport.decision.d4.situation": "Unsure about hours",
    "transport.decision.d4.suggestion": "Check the homepage for hours or contact us directly",

    // ── Experience ──
    "experience.hero.label": "The Experience",
    "experience.hero.title": "The Rhythm of a Meal",
    "experience.reserve.btn": "Reserve the Experience",

    // ── CRÈM ──
    "crem.hero.label": "CRÈM Dessert",
    "crem.hero.title": "Cake at the Table — A Sweet Finale",
    "crem.reserve.btn": "Reserve a Cake",
    "crem.banner.label": "Exclusive Collaboration",
    "crem.banner.title": "CRÈM Cake Table Reservation",
    "crem.banner.subtitle": "× CRÈM Exclusive Collab",
    "crem.banner.desc": "A complete celebration designed by two brands together.\nFrom the table to the cake, making every special moment more complete.",
    "crem.about.label": "About CRÈM",
    "crem.about.title": "A Dessert Brand Devoted to Cream",
    "crem.about.desc1": "CRÈM focuses on crafting high-quality cream-based desserts, centered around the core ingredient of \"fresh cream & butter.\"\nThrough deep research into cream, they pair different ingredients with cream to create the perfect flavor balance and ultimate taste in every dessert.",
    "crem.about.desc2": "For CRÈM, selecting cream is not about chasing the top-tier, but about leveraging professional knowledge of cream\nto discover its perfect compatibility with other ingredients, letting customers experience delicate and rich layers in every bite.",
    "crem.about.btn": "Visit CRÈM Website",
    "crem.steps.label": "How It Works",
    "crem.steps.title": "Four steps,\nfor a complete celebration.",
    "crem.steps.hint": "We handle all coordination with CRÈM. You just sit back and enjoy.",
    "crem.step1.title": "Reserve a Table",
    "crem.step1.desc": "Book via Inline for Deer's Hotpot Bistro and note the celebrant's name and dining time.",
    "crem.step2.title": "Choose a Cake",
    "crem.step2.desc": "Visit CRÈM's website (crem.tw) to select your celebration cake and note your reservation details.",
    "crem.step3.title": "We Handle It",
    "crem.step3.desc": "We follow up with CRÈM throughout to ensure the cake arrives at the right time.",
    "crem.step4.title": "Table Surprise",
    "crem.step4.desc": "The cake arrives after your meal. No need to worry about anything — just sit and celebrate.",
    "crem.cta.title": "Ready to make this celebration\nmore complete?",
    "crem.cta.btn1": "Reserve Deer's Hotpot",
    "crem.cta.btn2": "Choose a Cake at CRÈM",

    // ── Common ──
    "common.reserve": "Reserve Now",
    "common.learnMore": "Learn More",
    "common.back": "Back",
  },

  ja: {
    // ── Navbar ──
    "nav.home": "ホーム",
    "nav.brand": "ブランドストーリー",
    "nav.menu": "メニュー",
    "nav.space": "空間体験",
    "nav.awards": "受賞・メディア掲載",
    "nav.transport": "アクセス・駐車場",
    "nav.crem": "CRÈM ケーキテーブル予約",
    "nav.reserve": "今すぐ予約",
    "nav.shop": "フレッシュマーケット",
    "nav.close": "メニューを閉じる",
    "nav.open": "メニューを開く",

    // ── Footer ──
    "footer.contact": "お問い合わせ",
    "footer.hours": "営業時間",
    "footer.follow": "フォロー",
    "footer.findUs": "アクセス",
    "footer.address.city": "台北市信義区",
    "footer.address.street": "忠孝東路4段553巷6弄15号",
    "footer.navigate": "ナビゲーション",
    "footer.viewOnMaps": "Google マップで見る",
    "footer.gettingHere": "アクセス",
    "footer.transportDesc": "地下鉄・車・駐車場のご案内はアクセスページへ",
    "footer.transportLink": "アクセス・駐車場 →",
    "footer.copyright": "© 2026 初衷小鹿 Deer's Hotpot Bistro. All rights reserved.",
    "footer.hours.mon": "月曜日",
    "footer.hours.tue": "火曜日",
    "footer.hours.wed": "水曜日",
    "footer.hours.thu": "木曜日",
    "footer.hours.fri": "金曜日",
    "footer.hours.sat": "土曜日",
    "footer.hours.sun": "日曜日",

    // ── Home ──
    "home.tagline": "Deer's Hotpot Bistro · 台北信義",
    "home.hero.line1": "ただの鍋料理ではなく、",
    "home.hero.line2": "リズムのある",
    "home.hero.line3": "食卓体験。",
    "home.hero.cta": "テーブルを予約する",
    "home.philosophy.label": "Our Philosophy",
    "home.philosophy.title1": "賑やかな鍋料理はしません。",
    "home.philosophy.title2": "私たちが大切にしているのは、",
    "home.philosophy.title3": "食卓のリズムです。",
    "home.philosophy.desc": "前菜、スープ、熟成肉、ワインペアリング、デザートのフィナーレ。\nすべての瞬間がリズムの一部です。",
    "home.cores.label": "What We Do",
    "home.cores.title": "三つの柱が、完全な食卓体験を作る。",
    "home.cores.meat.en": "The Cut",
    "home.cores.meat.zh": "熟成肉",
    "home.cores.meat.subtitle": "熟成肉 · 厳選のプロフェッショナル",
    "home.cores.meat.desc": "ウェット熟成により、肉汁・脂肪の香り・柔らかさを保持。鍋料理の短時間加熱に最適で、肉本来の旨味をお楽しみいただけます。",
    "home.cores.soup.en": "The Broth",
    "home.cores.soup.zh": "日本最高級乾物",
    "home.cores.soup.subtitle": "『日本最高級乾物』出汁の深い味わい",
    "home.cores.soup.desc": "黄金色に輝く透明な出汁を長時間かけて丁寧に仕上げました。鰹節の燻製の深み、昆布・椎茸の温かな香りが口の中で層を成して広がります。",
    "home.cores.dessert.en": "The Finale",
    "home.cores.dessert.zh": "デザートとワイン",
    "home.cores.dessert.subtitle": "メイン鍋からデザートとワインへ",
    "home.cores.dessert.desc": "本当に記憶に残る体験は、着席からお食事後まで続きます。デザート、ワインセラー、テーブルのリズムが共に夕食を完成させます。",
    "home.narrative.label": "The Experience",
    "home.narrative.title": "食卓のリズムはこうして展開する。",
    "home.narrative.step1.title": "前菜が味覚を目覚めさせる",
    "home.narrative.step1.body": "満腹のためではなく、準備のために。\n一皿の前菜が、食卓のリズムをゆっくりと開く。",
    "home.narrative.step2.title": "出汁が始まると、ペースが落ちる",
    "home.narrative.step2.body": "食材の味を邪魔しない澄んだ出汁。\nすべての一口に、その場所がある。",
    "home.narrative.step3.title": "肉に調味料は不要",
    "home.narrative.step3.body": "熟成肉はそれ自体が答え。\n出汁だけ、時間だけ。",
    "home.narrative.step4.title": "最後に、デザートのための時間を",
    "home.narrative.step4.body": "素晴らしい食卓は、メインが終わっても散会すべきではない。\nデザートは、お互いのために時間を残す方法。",
    "home.space.label": "The Space",
    "home.space.title": "邪魔されるべきでない瞬間のために",
    "home.space.desc": "私たちが大切にしているのは、食べ物だけではありません。\nゆっくりと味わうべき瞬間のために。",
    "home.trust.label": "Trust",
    "home.trust.rating": "4.6 星",
    "home.trust.ratingDesc": "Google 評価",
    "home.trust.reviews": "500件以上のレビュー",
    "home.trust.reviewsDesc": "実際のお客様の声",
    "home.trust.years": "5年以上",
    "home.trust.yearsDesc": "ブランドの歴史",
    "home.cta.label": "Reservation",
    "home.cta.title": "あなたのテーブルをご予約ください",
    "home.cta.desc": "すべてのテーブルは、ゆっくりと味わうべき瞬間です。",
    "home.cta.btn": "今すぐ予約",
    "home.notice.label": "営業時間のお知らせ",

    // ── Home (TrustSection) ──
    "home.trust.googleReviews": "Google レビュー",
    "home.trust.reviewCount": "{n}件の Google レビュー",
    "home.trust.viewReviews": "Google レビューを見る ↗",
    "home.trust.authentic1": "レビューのためにギフトを贈ったり、",
    "home.trust.authentic2": "お客様に評価をお願いしたりはしません。",
    "home.trust.authenticSub": "すべてのレビューは、真実なお食事の記憶です。",
    "home.trust.recognition": "Recognition",
    "home.trust.award1.year": "2023 · 台北市鳔料理大会",
    "home.trust.award1.title": "2023 台北トップ10鳔料理",
    "home.trust.award2.year": "2024 · 台北市鳔料理大会",
    "home.trust.award2.title": "2024 台湾トップ30鳔料理",
    "home.trust.award3.year": "2024 · &Premium Japan",
    "home.trust.award3.title": "日本のライフスタイル雑誌《&Premium》年間掌載",
    "home.trust.award3.desc": "「美しい生活のガイド」をコンセプトに、上質な雰囲気で人気の日本生活雑誌",

    // ── Home (CRÈM section) ──
    "home.crem.imgTitle": "テーブルからケーキまで、一条コースのセレブレーションサービス。",
    "home.crem.imgTitleMobile1": "一条コースのセレブレーション、",
    "home.crem.imgTitleMobile2": "テーブルからケーキまで。",
    "home.crem.desc1": "初衷小鹿 × CRÈM コラボレーション、",
    "home.crem.desc2": "すべてのお祝いにスペシャルケーキを。",
    "home.crem.descSub": "二つのブランドが共創する、完全なお祝いのデザイン。",
    "home.crem.step1.label": "席の予約",
    "home.crem.step1.desc": "Inlineでオンライン予約、お祝いの方とお食事の時間をメモ",
    "home.crem.step2.label": "ケーキを選ぶ",
    "home.crem.step2.desc": "CRÈM公式サイトでケーキを選び、小鹿の予約情報をメモ",
    "home.crem.step3.label": "おまかせください",
    "home.crem.step3.desc": "CRÈMとの調整はすべて当店が担当、ケーキの時間通りの届けを確保",
    "home.crem.step4.label": "テーブルサプライズ",
    "home.crem.step4.desc": "食後にケーキ登場—何も心配せず、ただ席に座ってお祝いを楽しんで",
    "home.crem.ctaDesc": "何も心配いらない、あなただけのスペシャルなお祝い。",
    "home.crem.ctaBtn": "セレブレーションテーブルを予約",

    // ── Home (CTA section) ──
    "home.cta.finalTitle": "テーブルを予約する",
    "home.cta.finalDesc": "大切な人のために、時間を取り置いて。",
    "home.cta.finalBtn": "今すぐ予約",

    // ── Home (Cores updated subtitles) ──
    "home.cores.soup.subtitle2": "静岡本枯節 · 北海道羅臼昆布 · 宮崎香信椎茸",
    "home.cores.soup.desc2": "三種のプレミアム日本乾物を数時間かけてコトコト照らした出汁。甜み清らかで人工甘味料不使用——出汁は料理の魂であり、背景ではありません。",
    "home.cores.meat.subtitle2": "SRF和牛 · イベリコ豚 · グラスフェッドラム",
    "home.cores.meat.desc2": "レストラングレードの肉、ウエットエイジング処理。肉汁と脂躪の香りを保持し、鳔料理にもこだわりを。",
    "home.cores.dessert.subtitle2": "パティシエ · ソムリエ・キュレートワインリスト",
    "home.cores.dessert.desc2": "デザートは脇役ではありません。スパークリングワインのペアリングからデザートのフィナーレスまで——食事はメイン後に終わるべきではありません。",
    "home.cores.title2": "三つの柱が、完全な食卓体験を作る。",

    // ── Home (Space section updated) ──
    "home.space.cta": "空間体験 ⇢",
    "home.space.title2": "あなたたちのためのテーブル、",
    "home.space.title2b": "理由は不要。",

    // ── Home (Narrative CTA) ──
    "home.narrative.ctaReady": "準備はよろしいですか？",
    "home.narrative.ctaBtn": "テーブルを予約する",

    // ── Brand ──
    "brand.hero.label": "Brand Story",
    "brand.hero.title": "ブランドストーリー",
    "brand.hero.subtitle": "人生で最も忘れやすいのは、初心です。",
    "brand.origin.label": "The Origin",
    "brand.origin.title": "台湾一周の旅、一つの気づき。",
    "brand.origin.p1": "創業者の小鹿は、人生の方向性を失っていた頃、台湾一周の旅に出ました。台東の初鹿に追り着いた時、ある先住民の夫婦に温かく歓待されました。",
    "brand.origin.p2": "夫婦は彼に、先住民の言葉で「鹿」は「純粋」と「シンプル」を象徴すると語りました。豊かでなくても、滿足と幸福を感じている夫婦の姿に気づきました。",
    "brand.origin.p3": "「鹿」の意味のように、心の純粹な幸福こそが人生の終着点だと気づきました。旅の後、彼は自分の「初心」を見つめ直し、迷っている人たちに「幸福の意味」を再発見してほしいと願い、店名を「初衷小鹿」と名付けました。",
    "brand.stats.founded": "台北信義區創業",
    "brand.stats.rating": "Google 評価",
    "brand.stats.top10": "2023 台北鳘物大会トップ10",
    "brand.stats.top30": "2024 台湾トップ30鳘物",
    "brand.stats.reviews": "件のレビュー",
    "brand.commitment.label": "Our Commitment",
    "brand.commitment.title": "私たちのこだわり",
    "brand.commitment.c1.en": "Broth First",
    "brand.commitment.c1.zh": "天然出汁",
    "brand.commitment.c1.desc": "鴺節柴魚や野菜を長時間煮込んだ出汁。人工甘味料不使用。清らかで正直な、食材本来の誠実さ。",
    "brand.commitment.c2.en": "Curated Cuts",
    "brand.commitment.c2.zh": "吹選肉",
    "brand.commitment.c2.desc": "ウエットエイジング処理で肉汁、脂肉の香り、柔らかさを保持。各部位の特性に合わせた調理法で、一枚一枚に最適な位置を。",
    "brand.commitment.c3.en": "Present Service",
    "brand.commitment.c3.zh": "寄り添うサービス",
    "brand.commitment.c3.desc": "ペースを促せず、会話を遂げないサービス。寄り添いているが、場を占領しない。テーブルはあなたたちのもの。",
    "brand.commitment.c4.en": "CR\u00c8M Dessert",
    "brand.commitment.c4.zh": "セレブレーションケーキ",
    "brand.commitment.c4.desc": "CR\u00c8Mとのコラボで、テーブルからケーキまで一気通貫のセレブレーションサービスを提供。大切な瞬間を完結させます。",
    "brand.quote.label": "Our Philosophy",
    "brand.quote.text": "「スープは背景ではなく、料理の魂。」",
    "brand.quote.desc": "日本の高級乾物と天然野菜を長時間煮込んだ出汁。旨味を一口一口に封じ込め、食材本来の誠実さだけを残します。一口のスープが、初心の最も直接な表現。",
    "brand.quote.en": "Soul in every broth.",
    "brand.section1.label": "The Beginning",
    "brand.section1.title": "「初衷」についての物語",
    "brand.section2.label": "The Philosophy",
    "brand.section2.title": "良い鳘料理にはリズムがあると信じています。",
    "brand.section3.label": "The Name",
    "brand.section3.title": "なぜ「鹿」なのか？",
    "brand.cta.title": "リズムある食卓体験へ",
    "brand.cta.btn": "今すぐ予約",

    // ── Reservation ──
    "reservation.hero.label": "Reservation",
    "reservation.hero.title": "テーブルを予約する",
    "reservation.hero.subtitle": "大切な人のために時間を取っておく。",
    "reservation.booking.label": "Online Booking",
    "reservation.booking.note": "予約システムに問題がある場合は、Instagramまたは Facebook のダイレクトメッセージでご連絡ください。",
    "reservation.notice.label": "Booking Notice",
    "reservation.notice.title": "予約情報",
    "reservation.notice.n1.en": "Minimum Spend",
    "reservation.notice.n1.zh": "最低消費顕",
    "reservation.notice.n1.content": "ディナー: NT$600/人（個人計算）\nビジネスランチ: NT$300/人\n上記料金にサービス料上上乗せ10%",
    "reservation.notice.n2.en": "Hours",
    "reservation.notice.n2.zh": "営業時間",
    "reservation.notice.n2.content": "日曜日\u300011:30–15:00\u300017:30–22:30\n月曜日\u300012:00–15:00\u300018:00–22:00\n火曜日\u300012:00–15:00\u300018:00–22:00\n水曜日\u300012:00–15:00\u300018:00–22:00\n木曜日\u300012:00–15:00\u300018:00–22:00\n金曜日\u300012:00–15:00\u300017:30–22:30\n土曜日\u300011:30–15:00\u300017:30–22:30",
    "reservation.notice.n3.en": "Location",
    "reservation.notice.n3.zh": "住所",
    "reservation.notice.n3.content": "台北市信義区\n忠孝東路4段553巷6弄15号",
    "reservation.notice.n4.en": "Beverage Policy",
    "reservation.notice.n4.zh": "飲み物規定",
    "reservation.notice.n4.content": "NATURAミネラルウォーターまたは炭酸水のみ提供\nスピリッツはお断り\n持ち込みワイン: NT$500/本（コルクエージ）",
    "reservation.notes.label": "Important Notes",
    "reservation.notes.b1": "ご希望の時間帯と席を確保するため、3–7日前のご予約をお勧めします。",
    "reservation.notes.b2": "特別なご要望（包括部屋、セレブレーションデコレーション、食事制限）は備考欄にご記入ください。",
    "reservation.notes.b3": "一部の料理は供給状況や品質の問題で提供できない場合があります。",
    "reservation.notes.b4": "各セットには前菜、野菜プレート、サイドディッシュ、デザートが含まれます。",
    "reservation.notes.b5": "ビジネスランチは平日のみ。土日や祈日は提供しておりません。",
    "reservation.celeb.label": "Celebration Service",
    "reservation.celeb.title": "新サービス｜小鹿がお祝いケーキを準備します",
    "reservation.celeb.desc": "CRÈMとのコラボレーション。CRÈM公式サイトで注文し、予約名、日付、時間を備考欄に記入するだけ。制作・配送・テーブルプレゼンテーションは小鹿が全て引き受けます。",
    "reservation.celeb.s1.step": "01",
    "reservation.celeb.s1.title": "CRÈM公式サイトで注文",
    "reservation.celeb.s1.desc": "CRÈMのケーキ予約ページでサイズ（4・6・8インチ）を選んでオンラインでご注文ください。",
    "reservation.celeb.s2.step": "02",
    "reservation.celeb.s2.title": "予約情報を備考欄に記入",
    "reservation.celeb.s2.desc": "注文時に予約名、日付、時間を記入するだけ。レストランへの連絡は不要です。自動で手配りします。",
    "reservation.celeb.s3.step": "03",
    "reservation.celeb.s3.title": "小鹿が全て引き受けます",
    "reservation.celeb.s3.desc": "配送・冷蔵保管・テーブルプレゼンテーションまで全てお任せください。尺尺の主役とのダイニングをお楽しみください。",
    "reservation.celeb.highlights.label": "Service Highlights",
    "reservation.celeb.h1": "4・6・8インチケーキの注文（オンラインで簡単）",
    "reservation.celeb.h2": "レストランへの配送（受け取り不要）",
    "reservation.celeb.h3": "冷蔵保管（保冷の心配不要）",
    "reservation.celeb.h4": "予約情報の調整とテーブルサービス（連絡不要）",
    "reservation.celeb.h5": "キャンドルデコレーションもお任せ（演出不要）",
    "reservation.celeb.h6": "尺尺の主役とのダイニングを心から楽しむ",
    "reservation.celeb.cta.ready": "準備はよろしいですか？",
    "reservation.celeb.cta.desc": "CRÈM公式サイトでケーキを選び、予約名、日付、時間を記入するだけ。小鹿が全て引き受けます。",
    "reservation.celeb.cta.btn": "CRÈM公式サイトへ",

    // ── Menu ──
    "menu.hero.label": "Our Menu",
    "menu.hero.title": "すべての一皿が、リズムの一部。",
    "menu.reserve.btn": "今すぐ予約",
    "menu.note": "メニューと価格は季節により変更になる場合があります。現地でご確認ください。",
    "menu.hero.h1": "メニュー",
    "menu.hint": "画像をクリックして拡大 · 左右スワイプまたは ← → キーでページ移動 · 価格はすべて10%サービス料加算",
    "menu.lightbox.close": "どこかをクリックして閉じる",
    "menu.cat.all": "全メニュー",
    "menu.cat.surf": "海鮮＆肉セット",
    "menu.cat.beef": "牛肉セット",
    "menu.cat.pork": "豚肉セット",
    "menu.cat.lamb": "ラムセット",
    "menu.cat.seafood": "海鮮セット",
    "menu.cat.chicken": "鶏肉 / ベジタリアン",
    "menu.cat.sides": "単品サイド",
    "menu.cat.lunch": "ビジネスランチ",
    "menu.cat.drinks": "全ドリンク",
    "menu.drink.glass": "赤｜白｜スパークリング/グラス",
    "menu.drink.red": "赤ワイン/ボトル",
    "menu.drink.white": "白ワイン/ボトル",
    "menu.drink.sparkling": "スパークリング/ボトル",
    "menu.drink.beer": "ビール",
    "menu.drink.juice": "ジュース/ソフトドリンク",
    "menu.label.intro": "ブランド理念",
    "menu.label.surf": "海鮮＆肉セット",
    "menu.label.beef": "牛肉セット",
    "menu.label.pork": "豚肉セット",
    "menu.label.chicken": "鶏肉 / ベジタリアン",
    "menu.label.lamb": "ラムセット",
    "menu.label.seafood": "海鮮セット",
    "menu.label.sides1": "おいしいサイド",
    "menu.label.sides2": "手作りペースト / 餃子",
    "menu.label.sides3": "ワンタン / ボール類",
    "menu.label.sides4": "海鮮単品",
    "menu.label.sides5": "魚類単品",
    "menu.label.sides6": "野菜サイド",
    "menu.label.lunch1": "ビジネスランチ",
    "menu.label.lunch2": "ランチ牛肉",
    "menu.label.lunch3": "ランチ豚肉",
    "menu.label.lunch4": "ランチラム / 海鮮",
    "menu.label.lunch5": "ランチデザート",
    "menu.label.quote": "ブランドの言葉",

    // ── Space ──
    "space.hero.label": "Space Experience",
    "space.hero.title": "空間体験",
    "space.intro.p1": "空間はただの背景ではありません。\nそれはこの食事の最初の一言です。",
    "space.intro.p2": "黒稺、木質、暖かな銅の照明。\nすべての細部は、目の前の人に集中できるよう設計されています。",
    "space.sec1.label": "01 — Exterior",
    "space.sec1.title": "外観と入口",
    "space.sec2.label": "02 — Dining Area",
    "space.sec2.title": "ダイニングエリア",
    "space.quote.en": "\"The right distance between tables is a form of respect.\"",
    "space.quote.zh": "テーブル間の適切な距離は、尊重の一形態です。",
    "space.sec3.label": "03 — Details & Bar",
    "space.sec3.title": "細部とバー",
    "space.sec4.label": "04 — Location",
    "space.sec4.title": "アクセスとナビゲーション",
    "space.navigate.btn": "↗ ナビゲーション",
    "space.googlemaps.btn": "Google Mapsで見る",
    "space.cta.quote": "写真では伝わらない雰囲気が\nあります。",
    "space.reserve.btn": "Reserve a Table",

    // ── Awards ──
    "awards.hero.label": "Achievements & Press",
    "awards.hero.title": "受賞歴・雑誌掲載",
    "awards.hero.desc": "すべての認定は、私たちへのリマインダー。\nすべてのダイニング体験をより良くするために。",
    "awards.taiwan30.label": "2024 \u00b7 台北市鍋物コンテスト",
    "awards.taiwan30.title": "2024 台湾トップ30鍋物",
    "awards.taiwan30.subtitle": "Taiwan International Hotpot Awards \u2014 Top 30",
    "awards.taiwan30.desc": "台北から台湾全土へ、より大きな舞台で再び審査員に認められ、\n台湾年間トップ30大鍋物レストランに選出されました。",
    "awards.premium.label": "2024 \u00b7 &Premium Japan",
    "awards.premium.title": "日本のライフスタイル雑誌《&Premium》",
    "awards.premium.subtitle": "The Guide To A Better Life",
    "awards.premium.desc": "\u300cより良い生活のガイド\u300dをコンセプトにした日本の人気雑誌《&Premium》が、\n台湾のセレクトレストランに小鹿を掲載しました。",
    "awards.taipei10.label": "2023 \u00b7 台北鍋物アワード",
    "awards.taipei10.title": "台北市政府鍋物アワード TOP 10",
    "awards.taipei10.subtitle": "Taipei International Hotpot Awards \u2014 Top 10",
    "awards.taipei10.desc": "台北市政府主催の\u300c美食在台北\u30fb鍋物アワード\u300dで、\n小鹿は全国数千の参加店の中から頑張り、トップ10に選ばれました。",
    "awards.press.label": "Press Coverage",
    "awards.press.title": "メディア掃載",
    "awards.media.label": "Press Coverage",
    "awards.media.title": "メディア掃載",
    "awards.media.vogue.title": "Vogue Taiwan 特集",
    "awards.media.vogue.desc": "ファッションメディア Vogue Taiwan が特集を掲載し、初衷小鹿のブランド哲学とダイニング体験を深く紹介。",
    "awards.media.chinatimes.title": "工商時報掲載",
    "awards.media.chinatimes.desc": "経済メディア工商時報が飲食ブランドの角度から初衷小鹿のブランドストーリーと市場ポジショニングを深度掲載。",
    "awards.media.elle.title": "ELLE ライフガイド",
    "awards.media.elle.desc": "国際ファッション誌 ELLE が初衷小鹿を台北大巨蛋周辺のグルメガイドに掃載。",
    "awards.media.or.title": "旅讀 Or ピックアップ",
    "awards.media.or.desc": "旅行ライフスタイル誌旅讀 Or が特別推薦し、台北セレクトレストランリストに掃載。",
    "awards.reviews.label": "Google Reviews",
    "awards.reviews.title": "4.6星の裏側",
    "awards.reviews.count": "{count}件の本物のレビュー",
    "awards.reviews.count.fallback": "1,600+件の本物のレビュー",
    "awards.reviews.view": "Google Mapsで全レビューを見る \u2197",
    "awards.reviews.p1": "ゲストにレビューを依頼したことは一度もありません",
    "awards.reviews.p2": "レビュープレゼントキャンペーンは行っていません",
    "awards.reviews.p3": "偽レビューを購入したことは一度もありません",
    "awards.reviews.desc": "お客様一人ひとりの本物のフィードバックを一つ一つ集め、\nすべての進歩の指針にしています。",
    "awards.cta.text": "これらの認定が、すべての\nダイニング体験をより良くする激励になっています。",
    "awards.reserve.btn": "Reserve a Table",
    "awards.cta.title": "これらの認定が、すべての\nダイニング体験をより良くする激励になっています。",
    "awards.cta.btn": "テーブルを予約",
    "awards.premium.jul.desc": "2024年7月号《&Premium》は「台湾精選レストラン」をテーマに、初衷小鹿を推薦リストに掲載し、独自の鳘物体験とブランド哲学を紹介。",
    "awards.premium.oct.desc": "2024年10月号《&Premium》は再度初衷小鹿を掲載し、台北を代表するレストランとしての地位を認めました。",
    "awards.google.reviewsUnit": "件のレビュー",
    "awards.google.reviewsDefault": "1,626件のレビュー",
    "awards.google.viewAll": "Google Mapsで全レビューを見る ↗",
    "awards.google.rule1": "ゲストにレビューを依頼したことは一度もありません",
    "awards.google.rule2": "レビュープレゼントキャンペーンは行っていません",
    "awards.google.rule3": "偵レビューを購入したことは一度もありません",
    "awards.google.desc": "お客様一人ひとりの本物のフィードバックを一つ一つ集め、\nすべての進歩の指针にしています。",

    // ── Transport ──
    "transport.hero.label": "Getting Here",
    "transport.hero.title": "アクセスのご案内",
    "transport.hero.subtitle": "信義区の静かな谷間に位置\n事前にアクセス方法をご確認ください",
    "transport.hero.navigate.btn": "レストランへナビ",
    "transport.hero.parking.btn": "駐車場を確認",
    "transport.address.label": "住所",
    "transport.navigate.btn": "ナビゲーション",
    "transport.mrt.label": "地下鉄",
    "transport.bus.label": "バス",
    "transport.drive.label": "車",
    "transport.parking.label": "駐車場",
    "transport.overview.label": "Getting Here",
    "transport.overview.title": "最適なアクセス方法を選んでください",
    "transport.mrt.title": "地下鉄でのアクセス",
    "transport.mrt.line": "板南線 · 市政府駅",
    "transport.mrt.line.sub": "Bannan Line · City Hall Station",
    "transport.mrt.step1": "1番出口から出る",
    "transport.mrt.step2": "忠孝東路沿いに東へ歩く",
    "transport.mrt.step3": "徒歩約400m、5分程度",
    "transport.mrt.navigate.btn": "地下鉄ナビ",
    "transport.bus.title": "バスでのアクセス",
    "transport.bus.stop.label": "バス停",
    "transport.bus.routes.label": "利用可能な路線",
    "transport.bus.navigate.btn": "バスナビ",
    "transport.parking.title": "車でのアクセス",
    "transport.parking.desc": "レストランは谷間に位置し、街路駐車は限られています。近くの駐車場に駐車して徒歩でお赴きください。",
    "transport.parking.walk": "徒歩距離",
    "transport.parking.feature": "特徴",
    "transport.parking.spaces": "台数",
    "transport.parking.address": "住所",
    "transport.parking.navigate.btn": "駐車場へナビ",
    "transport.lot1.badge": "おすすめ",
    "transport.lot1.name": "松山高校地下駐車場",
    "transport.lot1.address": "基隆路一段 156号 B1",
    "transport.lot1.walk": "徒歩約3分",
    "transport.lot1.feature": "最も近く、スムーズなアクセスに最適",
    "transport.lot1.spaces": "経226台、年24時営業",
    "transport.lot2.badge": "代替",
    "transport.lot2.name": "俥亭駐車基隆路第2場",
    "transport.lot2.address": "基隆路一段176巷1号",
    "transport.lot2.walk": "徒歩2分",
    "transport.lot2.feature": "レストラン近く、迅速駐車に便利",
    "transport.lot2.spaces": "24時間営業、台数は現地でご確認ください",
    "transport.lot3.badge": "週末代替",
    "transport.lot3.name": "台北文創ビル有料駐車場",
    "transport.lot3.address": "信義区ヤンチャン路88号",
    "transport.lot3.walk": "徒歩8分",
    "transport.lot3.feature": "松山文化園内、台数充分、週末ピーク時に最適",
    "transport.lot3.spaces": "24時間営業、事前にリアルタイムの空き状況をご確認ください",
    "transport.decision.label": "Quick Guide",
    "transport.decision.title": "アクセス方法がわからない方へ",
    "transport.map.label": "Illustrated Map",
    "transport.map.title": "周辺アクセスマップ",
    "transport.map.zoom": "クリックで拡大",
    "transport.sticky.navigate": "ナビ",
    "transport.sticky.mrt": "地下鉄アクセス",
    "transport.sticky.parking": "駐車場",
    "transport.card.mrt.en": "MRT",
    "transport.card.mrt.zh": "地下鉄",
    "transport.card.mrt.desc": "市政府駅 1番出口\n徒歩5分程度",
    "transport.card.bus.en": "Bus",
    "transport.card.bus.zh": "バス",
    "transport.card.bus.desc": "市府バスターミナル周辺\n複数の路線でアクセス可",
    "transport.card.drive.en": "Drive",
    "transport.card.drive.zh": "車",
    "transport.card.drive.desc": "近くの駐車場に駐車\n徒歩5〜10分程度",
    "transport.card.taxi.en": "Taxi / Uber",
    "transport.card.taxi.zh": "タクシー",
    "transport.card.taxi.desc": "住所入力で直接アクセス\n全タクシーアプリ対応",
    "transport.decision.d1.situation": "最も便利な方法",
    "transport.decision.d1.suggestion": "地下鉄で市政府駅まで行き、徒歩でお赴きください",
    "transport.decision.d2.situation": "市内からのアクセス",
    "transport.decision.d2.suggestion": "バスまたは地下鉄どちらでも便利です",
    "transport.decision.d3.situation": "家族での来店",
    "transport.decision.d3.suggestion": "車で近くの駐車場に駐車し、徒歩でお赴きください",
    "transport.decision.d4.situation": "営業時間の確認",
    "transport.decision.d4.suggestion": "ホームページの営業時間をご確認いただくか、直接お問い合わせください",

    // ── Experience ──
    "experience.hero.label": "The Experience",
    "experience.hero.title": "食卓のリズム",
    "experience.reserve.btn": "体験を予約",

    // ── CRÈM ──
    "crem.hero.label": "CRÈM Dessert",
    "crem.hero.title": "テーブルでケーキ — 甘いフィナーレ",
    "crem.reserve.btn": "ケーキを予約",
    "crem.banner.label": "Exclusive Collaboration",
    "crem.banner.title": "CRÈMケーキテーブル予約",
    "crem.banner.subtitle": "× CRÈM コラボレーション",
    "crem.banner.desc": "二つのブランドが共創する、完整なお祝いのデザイン。\nテーブルからケーキまで、大切な瞬間をより完全に。",
    "crem.about.label": "About CRÈM",
    "crem.about.title": "クリームに専念するスイーツブランド",
    "crem.about.desc1": "CRÈMは「フレッシュクリーム & バター」をコア食材に、高品質なクリームスイーツの制作に専念しています。\nクリームへの深い研究を通じて、異なる食材とクリームを組み合わせ、各クリームスイーツの味覚バランスと極致の風味を創り出しています。",
    "crem.about.desc2": "CRÈMにとってクリームの選択は単に最高級を追うのではなく、\nクリームの専門知識を活かして他の食材との完美な相性を見つけ、一口で細腐さと豊かさを感じていただけるようにしています。",
    "crem.about.btn": "CRÈM公式サイトへ",
    "crem.steps.label": "How It Works",
    "crem.steps.title": "4つのステップで、\n完全なお祝いを完成。",
    "crem.steps.hint": "CRÈMとの連絡は小鹿が全て対応します。ご安心してお座りください。",
    "crem.step1.title": "席を予約",
    "crem.step1.desc": "Inlineで初衷小鹿を予約し、お祝いの方のお名前とご来店時間を備考欄にお書きください。",
    "crem.step2.title": "ケーキを選ぶ",
    "crem.step2.desc": "CRÈM公式サイト（crem.tw）でお祝いケーキを選び、初衷小鹿の予約情報を備考欄にお書きください。",
    "crem.step3.title": "小鹿が対応",
    "crem.step3.desc": "ケーキが正しい時間に届くよう、CRÈMとの連絡を全て小鹿が行います。",
    "crem.step4.title": "テーブルサプライズ",
    "crem.step4.desc": "食後にケーキが登場。何も心配いりません。ただ座ってお祝いを楽しんでください。",
    "crem.cta.title": "このお祝いを\nもっと完全にしませんか？",
    "crem.cta.btn1": "初衷小鹿を予約",
    "crem.cta.btn2": "CRÈMでケーキを選ぶ",

    // ── Common ──
    "common.reserve": "今すぐ予約",
    "common.learnMore": "詳しく見る",
    "common.back": "戻る",
  },

  ko: {
    // ── Navbar ──
    "nav.home": "홈",
    "nav.brand": "브랜드 스토리",
    "nav.menu": "메뉴",
    "nav.space": "공간 체험",
    "nav.awards": "수상 및 미디어",
    "nav.transport": "오시는 길",
    "nav.crem": "CRÈM 케이크 테이블 예약",
    "nav.reserve": "지금 예약",
    "nav.shop": "신선 마켓",
    "nav.close": "메뉴 닫기",
    "nav.open": "메뉴 열기",

    // ── Footer ──
    "footer.contact": "연락처",
    "footer.hours": "영업시간",
    "footer.follow": "팔로우",
    "footer.findUs": "찾아오시는 길",
    "footer.address.city": "타이베이시 신이구",
    "footer.address.street": "중샤오동로 4단 553항 6弄 15호",
    "footer.navigate": "길 안내",
    "footer.viewOnMaps": "Google 지도에서 보기",
    "footer.gettingHere": "오시는 길",
    "footer.transportDesc": "지하철, 자동차, 주차 안내 — 오시는 길 페이지 참조",
    "footer.transportLink": "오시는 길 →",
    "footer.copyright": "© 2026 초충샤오루 Deer's Hotpot Bistro. All rights reserved.",
    "footer.hours.mon": "월요일",
    "footer.hours.tue": "화요일",
    "footer.hours.wed": "수요일",
    "footer.hours.thu": "목요일",
    "footer.hours.fri": "금요일",
    "footer.hours.sat": "토요일",
    "footer.hours.sun": "일요일",

    // ── Home ──
    "home.tagline": "Deer's Hotpot Bistro · 타이베이 신이",
    "home.hero.line1": "단순한 훠궈가 아닌,",
    "home.hero.line2": "리듬 있는",
    "home.hero.line3": "식탁 경험.",
    "home.hero.cta": "테이블 예약하기",
    "home.philosophy.label": "Our Philosophy",
    "home.philosophy.title1": "우리는 시끌벅적한 훠궈를 하지 않습니다.",
    "home.philosophy.title2": "우리가 중요하게 생각하는 것은",
    "home.philosophy.title3": "식탁의 리듬입니다.",
    "home.philosophy.desc": "전채, 육수, 숙성 고기, 와인 페어링, 디저트 피날레.\n모든 순간이 리듬의 일부입니다.",
    "home.cores.label": "What We Do",
    "home.cores.title": "세 가지 핵심이 완벽한 식탁 경험을 만든다.",
    "home.cores.meat.en": "The Cut",
    "home.cores.meat.zh": "숙성 고기",
    "home.cores.meat.subtitle": "숙성 고기 · 엄선된 전문가",
    "home.cores.meat.desc": "습식 숙성으로 육즙, 지방 향, 부드러움을 보존합니다. 훠궈의 짧은 가열 방식에 최적화되어 고기 본연의 맛을 즐길 수 있습니다.",
    "home.cores.soup.en": "The Broth",
    "home.cores.soup.zh": "일본 프리미엄 건어물",
    "home.cores.soup.subtitle": "『일본 프리미엄 건어물』 육수의 깊은 풍미",
    "home.cores.soup.desc": "황금빛 투명한 건어물 육수를 오랜 시간 정성껏 끓였습니다. 가쓰오부시의 훈제 깊이, 다시마와 표고버섯의 따뜻한 향이 입안에서 층층이 펼쳐집니다.",
    "home.cores.dessert.en": "The Finale",
    "home.cores.dessert.zh": "디저트와 와인",
    "home.cores.dessert.subtitle": "메인 냄비에서 디저트와 와인으로",
    "home.cores.dessert.desc": "진정으로 기억에 남는 경험은 착석부터 식사 후까지 이어집니다. 디저트, 와인 캐비닛, 테이블의 리듬이 함께 저녁 식사를 완성합니다.",
    "home.narrative.label": "The Experience",
    "home.narrative.title": "식탁의 리듬은 이렇게 펼쳐진다.",
    "home.narrative.step1.title": "전채가 미각을 깨운다",
    "home.narrative.step1.body": "배를 채우기 위해서가 아니라, 준비를 위해.\n한 접시의 전채가 식탁의 리듬을 천천히 열어간다.",
    "home.narrative.step2.title": "육수가 시작되면 페이스가 느려진다",
    "home.narrative.step2.body": "식재료의 맛을 빼앗지 않는 맑은 육수.\n모든 한 입이 제자리를 찾는다.",
    "home.narrative.step3.title": "고기에는 양념이 필요 없다",
    "home.narrative.step3.body": "숙성 고기는 그 자체가 답이다.\n육수만, 시간만.",
    "home.narrative.step4.title": "마지막으로, 디저트를 위한 시간을",
    "home.narrative.step4.body": "좋은 식탁은 메인이 끝난 후 바로 헤어져서는 안 된다.\n디저트는 서로를 위한 시간을 남기는 방법이다.",
    "home.space.label": "The Space",
    "home.space.title": "방해받아서는 안 되는 순간을 위해",
    "home.space.desc": "우리가 중요하게 생각하는 것은 음식만이 아닙니다.\n충분히 즐길 가치가 있는 순간들을 위해.",
    "home.trust.label": "Trust",
    "home.trust.rating": "4.6점",
    "home.trust.ratingDesc": "Google 평점",
    "home.trust.reviews": "500개 이상의 리뷰",
    "home.trust.reviewsDesc": "실제 고객 후기",
    "home.trust.years": "5년 이상",
    "home.trust.yearsDesc": "브랜드 역사",
    "home.cta.label": "Reservation",
    "home.cta.title": "당신의 테이블을 예약하세요",
    "home.cta.desc": "모든 테이블은 충분히 즐길 가치가 있는 순간입니다.",
    "home.cta.btn": "지금 예약",
    "home.notice.label": "최근 영업시간 변경",

    // ── Home (TrustSection) ──
    "home.trust.googleReviews": "Google 리뷰",
    "home.trust.reviewCount": "{n}건의 Google 리뷰",
    "home.trust.viewReviews": "Google 리뷰 보기 ↗",
    "home.trust.authentic1": "리뷰를 위한 선물을 제공하거나",
    "home.trust.authentic2": "고객에게 평가를 요청하지 않습니다.",
    "home.trust.authenticSub": "모든 리뷰는 진실한 식사의 기억입니다.",
    "home.trust.recognition": "Recognition",
    "home.trust.award1.year": "2023 · 타이베이시 후구요리 대회",
    "home.trust.award1.title": "2023 타이베이 상위 10 후구요리",
    "home.trust.award2.year": "2024 · 타이베이시 후구요리 대회",
    "home.trust.award2.title": "2024 대만 상위 30 후구요리",
    "home.trust.award3.year": "2024 · &Premium Japan",
    "home.trust.award3.title": "일본 라이프스타일 잡지 《&Premium》 연간 수록",
    "home.trust.award3.desc": "아름다운 삶의 가이드를 콘셉트로 한 일본의 인기 라이프스타일 잡지",

    // ── Home (CRÈM section) ──
    "home.crem.imgTitle": "테이블에서 케이크까지, 일관 서비스 세레뢨니.",
    "home.crem.imgTitleMobile1": "일관 세레뢨니 서비스,",
    "home.crem.imgTitleMobile2": "테이블에서 케이크까지.",
    "home.crem.desc1": "주충새루 × CRÈM 콜라보레이션,",
    "home.crem.desc2": "모든 축하에 스페셜 케이크를.",
    "home.crem.descSub": "두 브랜드가 함께 만드는 완전한 축하 디자인.",
    "home.crem.step1.label": "좌석 예약",
    "home.crem.step1.desc": "Inline에서 온라인 예약, 축하는 분과 식사 시간 메모",
    "home.crem.step2.label": "케이크 선택",
    "home.crem.step2.desc": "CRÈM 공식 사이트에서 케이크 선택, 주충새루 예약 정보 메모",
    "home.crem.step3.label": "저희가 담당합니다",
    "home.crem.step3.desc": "CRÈM과의 조율은 모두 저희가 담당, 케이크의 제시간 도착 보장",
    "home.crem.step4.label": "테이블 서프라이즈",
    "home.crem.step4.desc": "식사 후 케이크 등장—아무 걸정 없이 자리에 않아 축하를 즐기세요",
    "home.crem.ctaDesc": "아무 걸정 없는 나만의 스페셜 축하.",
    "home.crem.ctaBtn": "축하 테이블 예약하기",

    // ── Home (CTA section) ──
    "home.cta.finalTitle": "테이블 예약하기",
    "home.cta.finalDesc": "중요한 사람에게 시간을 선물하세요.",
    "home.cta.finalBtn": "지금 예약",

    // ── Home (Cores updated subtitles) ──
    "home.cores.soup.subtitle2": "시즈오카 혹카레부시 · 홈콴도 라우스 다시마 · 미야자키 코신 표고버섯",
    "home.cores.soup.desc2": "세 가지 프리미엄 일본 건어물을 수 시간 새워 만든 육수. 달콤하고 맑으며 인공 감미료 미사용——육수는 요리의 영혼이지 배경이 아닙니다.",
    "home.cores.meat.subtitle2": "SRF 와근 · 이베리코 돼지 · 초원 사육 양고기",
    "home.cores.meat.desc2": "레스토랑 등급 육류, 습식 숨성 처리. 육즙과 지방의 향기를 보존하여 후구요리에도 세련리함을.",
    "home.cores.dessert.subtitle2": "파티시에 · 소메리에 큐레이트 와인 리스트",
    "home.cores.dessert.desc2": "디저트는 조연이 아닙니다. 스파클링 와인 페어링부터 디저트 피날레까지——식사는 메인 후에 끝나서는 안 됩니다.",
    "home.cores.title2": "세 가지 핵심이 완벽한 식탁 경험을 만든다.",

    // ── Home (Space section updated) ──
    "home.space.cta": "공간 체험 ⇢",
    "home.space.title2": "당신들만의 테이블,",
    "home.space.title2b": "이유는 필요 없습니다.",

    // ── Home (Narrative CTA) ──
    "home.narrative.ctaReady": "준비되셨나요?",
    "home.narrative.ctaBtn": "테이블 예약하기",

    // ── Brand ──
    "brand.hero.label": "Brand Story",
    "brand.hero.title": "브랜드 스토리",
    "brand.hero.subtitle": "인생에서 가장 잊기 쉽은 것은 초심입니다.",
    "brand.origin.label": "The Origin",
    "brand.origin.title": "대만 일주 여행, 하나의 깨달음.",
    "brand.origin.p1": "창업자 시아루는 인생의 방향성을 잊었을 때 대만 일주 여행을 떠났습니다. 타이둥의 초루에 도착했을 때 원주민 부부에게 따뜻한 환대를 받았습니다.",
    "brand.origin.p2": "부부는 그에게 원주민 언어에서 ‘사슴’은 ‘순수함’과 ‘단순함’을 상징한다고 말했습니다. 부유하지 않아도 만족과 행복을 느끼는 부부의 모습에 깨달음을 얻었습니다.",
    "brand.origin.p3": "‘사슴’의 의미처럼 순수한 정신적 행복이ec9e야말로 인생의 최종 목적지임을 느꼈 그는 여행 후 자신의 ‘초심’을 돌아보며 마음을 되찾았고, 많은 사람들이 행복의 의미를 다시 발견하길 바라며 가게 이름을 ‘초심소루’로 지었습니다.",
    "brand.stats.founded": "타이페이 신의 구 창업",
    "brand.stats.rating": "Google 평점",
    "brand.stats.top10": "2023 타이페이 횠구 톱 10",
    "brand.stats.top30": "2024 대만 톱 30 횠구",
    "brand.stats.reviews": "건의 리뷰",
    "brand.commitment.label": "Our Commitment",
    "brand.commitment.title": "저희의 신념",
    "brand.commitment.c1.en": "Broth First",
    "brand.commitment.c1.zh": "천연 육수",
    "brand.commitment.c1.desc": "가쌓오부시, 야칄 등을 오래 끝인 육수. 인공 감미료 미사용. 맑고 정직한 식재의 진실함.",
    "brand.commitment.c2.en": "Curated Cuts",
    "brand.commitment.c2.zh": "엄선 고기",
    "brand.commitment.c2.desc": "습식 숫성으로 육즈, 지방의 향, 부드러움을 보존. 각 부위의 특성에 맞는 조리법으로 한 조각 한 조각에 최적의 위치를.",
    "brand.commitment.c3.en": "Present Service",
    "brand.commitment.c3.zh": "세심한 서비스",
    "brand.commitment.c3.desc": "페이스를 재촉하지 않고 대화를 방해하지 않는 서비스. 곳에 있지만 공간을 점령하지 않습니다. 테이블은 당신들의 것.",
    "brand.commitment.c4.en": "CR\u00c8M Dessert",
    "brand.commitment.c4.zh": "축하 케이크",
    "brand.commitment.c4.desc": "CR\u00c8M과의 콜라보로 테이블부터 케이크까지 일관된 축하 서비스 제공. 중요한 순간을 완성합니다.",
    "brand.quote.label": "Our Philosophy",
    "brand.quote.text": "“육수는 배경이 아니라 요리의 영혼입니다.”",
    "brand.quote.desc": "일본 프리미엄 건어물과 신선한 야칄를 오래 끝인 육수. 우마미를 한 모금 한 모금에 담아 식재의 진실함만 남깁니다. 한 모금의 육수가 초심의 가장 직접적인 표현.",
    "brand.quote.en": "Soul in every broth.",
    "brand.section1.label": "The Beginning",
    "brand.section1.title": "「초심」에 관한 이야기",
    "brand.section2.label": "The Philosophy",
    "brand.section2.title": "우리는 좋은 횠구에는 리듬이 있다고 믿습니다.",
    "brand.section3.label": "The Name",
    "brand.section3.title": "왜 「사슴」인가?",
    "brand.cta.title": "리듬 있는 식탁 체험으로",
    "brand.cta.btn": "지금 예약",

    // ── Reservation ──
    "reservation.hero.label": "Reservation",
    "reservation.hero.title": "테이블 예약하기",
    "reservation.hero.subtitle": "중요한 사람을 위해 시간을 남겨두세요.",
    "reservation.booking.label": "Online Booking",
    "reservation.booking.note": "예약 시스템에 문제가 있으면 Instagram 또는 Facebook 다이렉트 메시지로 연락해 주세요.",
    "reservation.notice.label": "Booking Notice",
    "reservation.notice.title": "예약 안내",
    "reservation.notice.n1.en": "Minimum Spend",
    "reservation.notice.n1.zh": "최소 소비",
    "reservation.notice.n1.content": "디너: NT$600/인(개인 계산)\n비즈니스 런치: NT$300/인\n위 가격에 10% 서비스 요금 추가",
    "reservation.notice.n2.en": "Hours",
    "reservation.notice.n2.zh": "영업시간",
    "reservation.notice.n2.content": "일요일\u300011:30–15:00\u300017:30–22:30\n월요일\u300012:00–15:00\u300018:00–22:00\n화요일\u300012:00–15:00\u300018:00–22:00\n수요일\u300012:00–15:00\u300018:00–22:00\n목요일\u300012:00–15:00\u300018:00–22:00\n금요일\u300012:00–15:00\u300017:30–22:30\n토요일\u300011:30–15:00\u300017:30–22:30",
    "reservation.notice.n3.en": "Location",
    "reservation.notice.n3.zh": "주소",
    "reservation.notice.n3.content": "타이베이시 신이구\n중샤동로 4단 553항 6누 15호",
    "reservation.notice.n4.en": "Beverage Policy",
    "reservation.notice.n4.zh": "음료 규정",
    "reservation.notice.n4.content": "NATURA 미네랄 워터 또는 탄산수만 제공\n증류는 불가\n와인 코르크에이지: NT$500/병",
    "reservation.notes.label": "Important Notes",
    "reservation.notes.b1": "원하는 시간대와 좌석을 확보하려면 3–7일 전 예약을 권장합니다.",
    "reservation.notes.b2": "특별 요청(프라이빗 룸메, 세레모니 데코레이션, 식이 제한)은 메모 란에 기재해 주세요.",
    "reservation.notes.b3": "일부 요리는 공급 상황이나 품질 문제로 제공되지 않을 수 있습니다.",
    "reservation.notes.b4": "각 세트에는 전식, 사이드 디시, 디저트가 포함됩니다.",
    "reservation.notes.b5": "비즈니스 런치는 평일에만 제공됩니다. 주말 및 공휴일에는 제공되지 않습니다.",
    "reservation.celeb.label": "Celebration Service",
    "reservation.celeb.title": "신규 서비스 | 소루가 축하 케이크를 준비합니다",
    "reservation.celeb.desc": "CRÈM과의 콜라보레이션. CRÈM 공식 사이트에서 주문하고 예약명, 날짜, 시간을 메모 란에 기재하면 제작·배송·테이블 프레젠테이션은 소루가 전부 담당합니다.",
    "reservation.celeb.s1.step": "01",
    "reservation.celeb.s1.title": "CRÈM 공식 사이트에서 주문",
    "reservation.celeb.s1.desc": "CRÈM 케이크 예약 페이지에서 사이즈(4·6·8인치)를 선택하고 온라인으로 주문하세요.",
    "reservation.celeb.s2.step": "02",
    "reservation.celeb.s2.title": "예약 정보 메모 란에 기재",
    "reservation.celeb.s2.desc": "주문 시 예약명, 날짜, 시간을 기재하면 됨니다. 레스토랑에 따로 연락할 필요가 없습니다.",
    "reservation.celeb.s3.step": "03",
    "reservation.celeb.s3.title": "소루가 다 담당합니다",
    "reservation.celeb.s3.desc": "배송·냉장 보관·테이블 프레젠테이션까지 전부 맡겨주세요. 주인공과의 식사를 맘껴 즉기세요.",
    "reservation.celeb.highlights.label": "Service Highlights",
    "reservation.celeb.h1": "4·6·8인치 케이크 주문(온라인, 간편함)",
    "reservation.celeb.h2": "레스토랑 배송(수령 불필요)",
    "reservation.celeb.h3": "냉장 보관(신선도 걱정 불필요)",
    "reservation.celeb.h4": "예약 정보 조율 및 테이블 서비스(따로 연락 불필요)",
    "reservation.celeb.h5": "취화 연출도 소루가 담당(직접 준비 불필요)",
    "reservation.celeb.h6": "주인공과의 식사를 진심으로 즉기세요",
    "reservation.celeb.cta.ready": "준비되셨나요?",
    "reservation.celeb.cta.desc": "CRÈM 공식 사이트에서 케이크를 선택하고 예약명, 날짜, 시간을 기재하면 나머지는 저희가 담당합니다.",
    "reservation.celeb.cta.btn": "CRÈM 공식 사이트 방문",

    // ── Menu ──
    "menu.hero.label": "Our Menu",
    "menu.hero.title": "모든 요리가 리듬의 일부.",
    "menu.reserve.btn": "지금 예약",
    "menu.note": "메뉴와 가격은 계절에 따라 변경될 수 있습니다. 현장에서 확인해 주세요.",
    "menu.hero.h1": "메뉴",
    "menu.hint": "이미지 클릭으로 확대 · 좌우 스와이프 또는 ← → 키로 페이지 이동 · 모든 가격에 10% 서비스 요금 추가",
    "menu.lightbox.close": "아무 곳이나 클릭하여 닫기",
    "menu.cat.all": "전체 메뉴",
    "menu.cat.surf": "해산물 & 고기 세트",
    "menu.cat.beef": "소고기 세트",
    "menu.cat.pork": "돼지고기 세트",
    "menu.cat.lamb": "양고기 세트",
    "menu.cat.seafood": "해산물 세트",
    "menu.cat.chicken": "닭고기 / 채식",
    "menu.cat.sides": "단품 사이드",
    "menu.cat.lunch": "비즈니스 런치",
    "menu.cat.drinks": "전체 음료",
    "menu.drink.glass": "레드｜화이트｜스파클링/잔",
    "menu.drink.red": "레드와인/병",
    "menu.drink.white": "화이트와인/병",
    "menu.drink.sparkling": "스파클링/병",
    "menu.drink.beer": "맥주",
    "menu.drink.juice": "주스/소프트드링크",
    "menu.label.intro": "브랜드 철학",
    "menu.label.surf": "해산물 & 고기 세트",
    "menu.label.beef": "소고기 세트",
    "menu.label.pork": "돼지고기 세트",
    "menu.label.chicken": "닭고기 / 채식",
    "menu.label.lamb": "양고기 세트",
    "menu.label.seafood": "해산물 세트",
    "menu.label.sides1": "맛있는 사이드",
    "menu.label.sides2": "수제 어묵 / 만두",
    "menu.label.sides3": "완탕 / 완자류",
    "menu.label.sides4": "해산물 단품",
    "menu.label.sides5": "생선 단품",
    "menu.label.sides6": "채소 사이드",
    "menu.label.lunch1": "비즈니스 런치",
    "menu.label.lunch2": "런치 소고기",
    "menu.label.lunch3": "런치 돼지고기",
    "menu.label.lunch4": "런치 양고기 / 해산물",
    "menu.label.lunch5": "런치 디저트",
    "menu.label.quote": "브랜드 문구",

    // ── Space ──
    "space.hero.label": "Space Experience",
    "space.hero.title": "공간 체험",
    "space.intro.p1": "공간은 단순한 배경이 아닙니다.\n이 식사의 첫 문장입니다.",
    "space.intro.p2": "검은 벨돌, 나무, 따뜻한 구리 조명.\n모든 세부 사항은 눈 앞의 사람에게 집중할 수 있도록 설계되었습니다.",
    "space.sec1.label": "01 — Exterior",
    "space.sec1.title": "외관 및 입구",
    "space.sec2.label": "02 — Dining Area",
    "space.sec2.title": "식사 공간",
    "space.quote.en": "\"The right distance between tables is a form of respect.\"",
    "space.quote.zh": "테이블 사이의 적절한 거리는 존중의 한 형태입니다.",
    "space.sec3.label": "03 — Details & Bar",
    "space.sec3.title": "세부 사항 및 바",
    "space.sec4.label": "04 — Location",
    "space.sec4.title": "위치 및 네비게이션",
    "space.navigate.btn": "↗ 네비게이션",
    "space.googlemaps.btn": "Google Maps에서 보기",
    "space.cta.quote": "사진으로는 전달할 수 없는\n분위기가 있습니다.",
    "space.reserve.btn": "Reserve a Table",

    // ── Awards ──
    "awards.hero.label": "Achievements & Press",
    "awards.hero.title": "수상 이력 및 언론 보도",
    "awards.hero.desc": "모든 인정은 저희에게 주는 리마인더입니다.\n모든 식사 체험을 더 나은 것으로 만들기 위해.",
    "awards.taiwan30.label": "2024 \u00b7 타이페이 남비 핫팟 대회",
    "awards.taiwan30.title": "2024 대만 TOP 30 핫팟",
    "awards.taiwan30.subtitle": "Taiwan International Hotpot Awards \u2014 Top 30",
    "awards.taiwan30.desc": "타이페이에서 대만 전체로, 더 큰 무대에서 다시 심사위원에게 인정받아,\n대만 연간 TOP 30 핫팟 레스토랑으로 선정되었습니다.",
    "awards.premium.label": "2024 \u00b7 &Premium Japan",
    "awards.premium.title": "일본 라이프스타일 잡지 \u300a&Premium\u300b",
    "awards.premium.subtitle": "The Guide To A Better Life",
    "awards.premium.desc": "'\ub354 나은 삶을 위한 가이드'\ub97c 콘셈트로 한 일본 인기 잡지 &Premium이,\n대만 선정 레스토랑에 소루를 소개했습니다.",
    "awards.taipei10.label": "2023 \u00b7 타이페이 핫팟 어워드",
    "awards.taipei10.title": "타이페이 시 정부 핫팟 어워드 TOP 10",
    "awards.taipei10.subtitle": "Taipei International Hotpot Awards \u2014 Top 10",
    "awards.taipei10.desc": "타이페이 시가 주최한 '미식재타이페이 핫팟 어워드'에서,\n소루는 전국 수천 개의 참가 레스토랑 중에서 떠올라 TOP 10에 선정되었습니다.",
    "awards.press.label": "Press Coverage",
    "awards.press.title": "언론 보도",
    "awards.media.label": "Press Coverage",
    "awards.media.title": "언론 보도",
    "awards.media.vogue.title": "Vogue Taiwan 특집",
    "awards.media.vogue.desc": "패션 미디어 Vogue Taiwan이 특집을 게재하여 초심소로의 브랜드 철학과 다이닝 체험을 심층 소개.",
    "awards.media.chinatimes.title": "공상시보 보도",
    "awards.media.chinatimes.desc": "경제 미디어 공상시보가 F&B 브랜드 관점에서 초심소로의 브랜드 스토리와 시장 포지셔닝을 심층 보도.",
    "awards.media.elle.title": "ELLE 라이프 가이드",
    "awards.media.elle.desc": "국제 패션 잡지 ELLE가 초심소로를 타이페이 도실 주변 미식 가이드에 수록.",
    "awards.media.or.title": "여독 Or 픽업",
    "awards.media.or.desc": "여행 라이프스타일 잡지 여독 Or가 특별 추천하여 타이페이 선정 레스토랑 리스트에 수록.",
    "awards.reviews.label": "Google Reviews",
    "awards.reviews.title": "4.6점 별점의 이면",
    "awards.reviews.count": "{count}건의 진짜 리뷰",
    "awards.reviews.count.fallback": "1,600+건의 진짜 리뷰",
    "awards.reviews.view": "Google Maps에서 모든 리뷰 보기 \u2197",
    "awards.reviews.p1": "게스트에게 리뷰를 요청한 적이 없습니다",
    "awards.reviews.p2": "리뷰 선물 이벤트를 진행한 적이 없습니다",
    "awards.reviews.p3": "가짜 리뷰를 구매한 적이 없습니다",
    "awards.reviews.desc": "각 게스트의 진짜 피드백을 하나하나 모아,\n모든 발전의 방침으로 삼고 있습니다.",
    "awards.cta.text": "이러한 인정들이 저희가 모든\n식사 체험을 더 나은 것으로 만들도록 격려합니다.",
    "awards.reserve.btn": "Reserve a Table",
    "awards.cta.title": "이러한 인정들이 저희가 모든\n식사 체험을 더 나은 것으로 만들도록 격려합니다.",
    "awards.cta.btn": "테이블 예약",
    "awards.premium.jul.desc": "2024년 7월호 《&Premium》은 '대만 선정 레스토랑'을 테마로 소루를 추천 리스트에 게재하여 독특한 항폩 체험과 브랜드 철학을 소개.",
    "awards.premium.oct.desc": "2024년 10월호 《&Premium》은 다시 소루를 게재하여 타이페이를 대표하는 레스토랑으로서의 위치를 인정했습니다.",
    "awards.google.reviewsUnit": "건의 리뷰",
    "awards.google.reviewsDefault": "1,626건의 리뷰",
    "awards.google.viewAll": "Google Maps에서 모든 리뷰 보기 ↗",
    "awards.google.rule1": "게스트에게 리뷰를 요청한 적이 없습니다",
    "awards.google.rule2": "리뷰 선물 이벤트를 진행한 적이 없습니다",
    "awards.google.rule3": "가짜 리뷰를 구매한 적이 없습니다",
    "awards.google.desc": "각 게스트의 진짜 피드백을 하나하나 모아,\n모든 발전의 방침으로 삼고 있습니다.",

    // ── Transport ──
    "transport.hero.label": "Getting Here",
    "transport.hero.title": "오시는 길 안내",
    "transport.hero.subtitle": "신의구 조용한 돌목길에 위치\n사전에 교통 수단을 확인해 주세요",
    "transport.hero.navigate.btn": "레스토랑 길 안내",
    "transport.hero.parking.btn": "주차 정보 확인",
    "transport.address.label": "주소",
    "transport.navigate.btn": "길 안내",
    "transport.mrt.label": "지하철",
    "transport.bus.label": "버스",
    "transport.drive.label": "자동차",
    "transport.parking.label": "주차",
    "transport.overview.label": "Getting Here",
    "transport.overview.title": "가장 편리한 교통 수단을 선택하세요",
    "transport.mrt.title": "지하철 이용",
    "transport.mrt.line": "판난선 · 시정부역",
    "transport.mrt.line.sub": "Bannan Line · City Hall Station",
    "transport.mrt.step1": "1번 출구로 나오세요",
    "transport.mrt.step2": "중산동로를 따라 동쪽으로 도보",
    "transport.mrt.step3": "도보 약 400m, 5분 소요",
    "transport.mrt.navigate.btn": "지하철 길 안내",
    "transport.bus.title": "버스 이용",
    "transport.bus.stop.label": "버스 정류장",
    "transport.bus.routes.label": "이용 가능 노선",
    "transport.bus.navigate.btn": "버스 길 안내",
    "transport.parking.title": "자동차 이용",
    "transport.parking.desc": "레스토랑 주변 도로변 주차는 제한적입니다. 근처 주차장에 주차 후 도보로 오시기를 권장합니다.",
    "transport.parking.walk": "도보 거리",
    "transport.parking.feature": "특징",
    "transport.parking.spaces": "주차 대수",
    "transport.parking.address": "주소",
    "transport.parking.navigate.btn": "주차장 길 안내",
    "transport.lot1.badge": "추천",
    "transport.lot1.name": "송산고등학교 지하 주차장",
    "transport.lot1.address": "기륨로 1단 156호 B1",
    "transport.lot1.walk": "도보 3분",
    "transport.lot1.feature": "가장 가까운 주차장, 빠른 접근에 적합",
    "transport.lot1.spaces": "약 226자리, 24시간 영업",
    "transport.lot2.badge": "대안",
    "transport.lot2.name": "차정 주차 기륨로 2장",
    "transport.lot2.address": "기륨로 1단 176골목 1호",
    "transport.lot2.walk": "도보 2분",
    "transport.lot2.feature": "식당 근처, 빠른 주차에 편리",
    "transport.lot2.spaces": "24시간 영업, 자리 수는 현장 확인",
    "transport.lot3.badge": "주말 대안",
    "transport.lot3.name": "타이페이 크리에이티브 파크 유료 주차장",
    "transport.lot3.address": "신의구 연창로 88호",
    "transport.lot3.walk": "도보 8분",
    "transport.lot3.feature": "송산 문화원 내부, 주말 피크시간에 적합",
    "transport.lot3.spaces": "24시간 영업, 사전에 실시간 주차 가능 여부 확인 권장",
    "transport.decision.label": "Quick Guide",
    "transport.decision.title": "오는 방법을 모르시나요?\n이렇게 선택하세요",
    "transport.map.label": "Illustrated Map",
    "transport.map.title": "주변 교통 안내도",
    "transport.map.zoom": "클릭하여 확대",
    "transport.sticky.navigate": "길 안내",
    "transport.sticky.mrt": "지하철 이용",
    "transport.sticky.parking": "주차 정보",
    "transport.card.mrt.en": "MRT",
    "transport.card.mrt.zh": "지하철",
    "transport.card.mrt.desc": "시정부역 1번 출구\n도보 5분 소요",
    "transport.card.bus.en": "Bus",
    "transport.card.bus.zh": "버스",
    "transport.card.bus.desc": "시정부 버스 터미널 근처\n다수 노선 이용 가능",
    "transport.card.drive.en": "Drive",
    "transport.card.drive.zh": "자동차",
    "transport.card.drive.desc": "근처 주차장 이용\n도보 5–10분 소요",
    "transport.card.taxi.en": "Taxi / Uber",
    "transport.card.taxi.zh": "택시",
    "transport.card.taxi.desc": "주소 입력으로 직접 이동\n모든 택시 앱 지원",
    "transport.decision.d1.situation": "가장 편리한 방법",
    "transport.decision.d1.suggestion": "지하철로 시정부역까지 가서 도보로 오세요",
    "transport.decision.d2.situation": "시내에서 오시는 분",
    "transport.decision.d2.suggestion": "버스나 지하철 모두 편리합니다",
    "transport.decision.d3.situation": "가족과 함께 오시는 분",
    "transport.decision.d3.suggestion": "자동차로 근처 주차장에 주차 후 도보로 오세요",
    "transport.decision.d4.situation": "영업시간 확인",
    "transport.decision.d4.suggestion": "홈페이지의 영업시간을 확인하시거나 직접 문의해 주세요",

    // ── Experience ──
    "experience.hero.label": "The Experience",
    "experience.hero.title": "식탁의 리듬",
    "experience.reserve.btn": "체험 예약",

    // ── CRÈM ──
    "crem.hero.label": "CRÈM Dessert",
    "crem.hero.title": "테이블 위의 케이크 — 달콤한 피날레",
    "crem.reserve.btn": "케이크 예약",
    "crem.banner.label": "Exclusive Collaboration",
    "crem.banner.title": "CRÈM 케이크 테이블 예약",
    "crem.banner.subtitle": "× CRÈM 콜라보레이션",
    "crem.banner.desc": "두 브랜드가 함께 만들어가는 완전한 축하 디자인.\n테이블부터 케이크까지, 소중한 순간을 더욱 완전하게.",
    "crem.about.label": "About CRÈM",
    "crem.about.title": "크림에 전념하는 디저트 브랜드",
    "crem.about.desc1": "CRÈM은 '생크림 & 버터'를 핵심 식재로 고품질 크림 디저트 제작에 전념합니다.\n크림에 대한 깊은 연구를 통해 다양한 식재와 크림을 조합하여 각 크림 디저트의 맛의 균형과 극치의 풍미를 만들어냅니다.",
    "crem.about.desc2": "CRÈM에게 크림 선택은 단순히 최고급을 추구하는 것이 아니라,\n크림에 대한 전문 지식을 활용하여 다른 식재와의 완벽한 궁합을 찾아, 한 입에 세세함과 풍부함을 느낄 수 있도록 합니다.",
    "crem.about.btn": "CRÈM 공식 웹사이트 방문",
    "crem.steps.label": "How It Works",
    "crem.steps.title": "4단계로,\n완전한 축하를 완성하세요.",
    "crem.steps.hint": "CRÈM과의 모든 연락은 소록이 담당합니다. 편안히 앉아 즐기세요.",
    "crem.step1.title": "자리 예약",
    "crem.step1.desc": "Inline으로 초충소록을 예약하고, 축하 대상자의 이름과 식사 시간을 비고란에 적어주세요.",
    "crem.step2.title": "케이크 선택",
    "crem.step2.desc": "CRÈM 공식 웹사이트(crem.tw)에서 축하 케이크를 선택하고, 초충소록 예약 정보를 비고란에 적어주세요.",
    "crem.step3.title": "소록이 대신합니다",
    "crem.step3.desc": "케이크가 정확한 시간에 도착하도록 CRÈM과의 모든 확인을 소록이 진행합니다.",
    "crem.step4.title": "테이블 서프라이즈",
    "crem.step4.desc": "식사 후 케이크가 등장합니다. 아무 걱정 없이 앉아서 축하를 즐기세요.",
    "crem.cta.title": "이 축하를\n더욱 완전하게 만들 준비가 되셨나요?",
    "crem.cta.btn1": "초충소록 예약",
    "crem.cta.btn2": "CRÈM에서 케이크 선택",

    // ── Common ──
    "common.reserve": "지금 예약",
    "common.learnMore": "자세히 보기",
    "common.back": "뒤로",
  },
};
